### ISSUE TITLE
Oddly named chapters are skipped

### ISSUE THREAD

**Issue by pancakegirl226** [tachiyomiorg/tachiyomi#10014]
### Steps to reproduce

> Open any manga that has chapters that are numbered in more than one way(ie has a chapter called "Prologue 1" and a different chapter called "Chapter 1")

> Finish reading one a chapter who shares it's number with another chapter 

> A chapter other than the next chapter is loaded

### Expected behavior

The next chapter should be loaded(ie "Prologue 1" > "Chapter 1", not "Prologue 1" > "Chapter 2")

### Actual behavior

A chapter other than the next chapter is loaded. For example, a series with the following chapters:
> Prologue 1
> Prologue 2
> Chapter 1
> Chapter 2

is read in the order "Prologue 1" > "Chapter 2" instead of the expected "Prologue 1" > "Prologue 2" > "Chapter 1" > "Chapter 2"

### Tachiyomi version

App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z) 

### Android version

Android version: 13 (SDK 33) Android build ID: TP1A.220624.014.A426USQU7EWI1

### Device

 Device brand: samsung Device manufacturer: samsung Device name: a42xuq Device model: SM-A426U

### Other details

This is a relatively old issue, I had figured someone else already reported it. From what I remember, this issue began when the feature for automatically skipping duplicates of a chapter was added.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by garvongithub** [comment]
This is because Tachiyomi does not follow source's order while reading, it instead follows the numbers parsed from the chapter titles. So here Prologue 1 is being picked up as chapter 1 and I think you have turned on 'skip duplicate chapters' so the original chapter 1 is being skipped and then the next parsed chapter 2 comes up. You can check how the chapters are being picked up by hiding chapter titles. I was just about to open a issue for this. 


| Orginal Titles  | Hidden Titles |
| ------------- | ------------- |
| ![image](https://github.com/tachiyomiorg/tachiyomi/assets/77321589/21a5813c-53f2-4947-9432-24a584d02f6e)  | ![image](https://github.com/tachiyomiorg/tachiyomi/assets/77321589/be0422be-d978-4455-a1c1-795ee442cf27)  |


Tachiyomi does not recognizes volumes **yet**. That's okay but Should not the above files be picked up as chapter 1,2,3,4,5. They are instead picked up as Chapter 2022 and 2023. This creates many problems. You cannot migrate smoothly. It marks all the chapter numbers less 2022 and 2023 as read. Marking chapter 1-5 as read should have been the correct behaviour. Also you can link tracking to these enteries. As they will update 2022 and 2023 every time on the site. Volume tracking is not supported **yet** but still I would have liked to link the tracking and manually update the chapters from the sheet within the app. I myself do not know anything about coding but I think [this document](https://wiki.kavitareader.com/en/guides/managing-your-files/manga#examples-of-naming-conventions-supported-out-of-the-box) should help for whoever decide to tackle this issue. This is Kavita, a self hosted book server. Its algorithm has always been successful for me for picking up correct chapter numbers and volumes.

**Comment by christmovies** [comment]
Maybe si this, select source title

**Comment by christmovies** [comment]
![Screenshot_2023-10-17-17-53-10-529_eu kanade tachiyomi debug](https://github.com/tachiyomiorg/tachiyomi/assets/97629848/e0c6b89a-bf69-4a78-8283-5042e4314807)
Maybe is this, select source title

**Comment by arkon** [comment]
See #3669

The chapter detection looks for chapter numbers and explicitly ignores volume numbers, but I doubt this will ever change.
