### ISSUE TITLE
Is there a way for Tachiyomi to detect volumes, and not chapters when using local manga? 

### ISSUE THREAD

**Issue by fighuass** [tachiyomiorg/tachiyomi#1117]
Almost all manga I read are zip archives containing volumes, not chapters. For example, some follow this format: Manga01 v01 ch01-12.zip

Is there a way to make Tachiyomi detect those as volumes, not chapters? Or at the very least, is there some sort of way to split the volume into separate archives, one chapter per archive?

**Comment by MercerBoi** [comment]
There is a way, though it'll take you some time. You need to unzip each of those volumes, separate the different chapters from within (this is the time consuming part) and turn them into individual .zip files (so that it's one chapter per .zip file) and then put them in a folder with the manga's name, and then moving that folder to the local folder. Suffice to say, if you haven't read the manga before, you're bound to get spoiled, as you'll need to go over the pages in order to separate the chapters.

**Comment by arkon** [comment]
This will probably never be done since the app has a heavy assumption based around chapters (number detection, tracking).
