### ISSUE TITLE
Open random manga from library

### ISSUE THREAD

**Issue by Vesnyx** [tachiyomiorg/tachiyomi#1248]
In #964, there was a mention of a random manga from each catalogue. I'm not requesting that, but rather one that will open a random manga that I've already added to my library.

Essentially, there will be a "Random" button at the top of the my library page that'll open a chapter from one of the manga that we have in the library. In the best case scenario, the random button would also have a set of options to choose from like: 

- Selecting from downloaded
- Selecting from unread
- Selecting the first unread chapter instead of the latest

**Comment by hXtreme** [comment]
What are your thoughts about the following:

Instead of a button that opens a random manga how about an option to sort your library randomly?

**Comment by Vesnyx** [comment]
Personally, I believe it takes away from the "randomness" aspect if a new sort is all that's happening. The way I envision the feature's use is that a user would have a large library but can't decide what to read. They'd hit the random button and be greeted with a randomly selected chapter, skipping the manga description view itself.

This also made me think of a different way to approach this. What if there was a "playlist" of sorts. Normally the reader loads the next chapter in the same manga. What if we implemented a playlist that the user could follow. This might make it easier to implement a randomize feature and might simply be a nice feature to have. If this sounds good, I can make a new issue regarding implementing this.

**Comment by Kongs23** [comment]
DO THIS ALREADY 😤😤😤😤😤

**Comment by Flat** [comment]
Do it yourself.

**Comment by Vesnyx** [comment]
Hahaha. I'll start working on it soon, been pretty busy recently.

**Comment by DorianK29** [comment]
[https://github.com/tachiyomiorg/tachiyomi/issues/4648#issuecomment-798924187](url)
I have manged to make this myself would love if it could get implemented! If there are any issues please ask.

**Comment by Vesnyx** [comment]
Made a pull request with your changes @DorianK29. Thanks!

**Comment by arkon** [comment]
This is in response to #4652, especially [the issue of overflowing menu items](https://github.com/tachiyomiorg/tachiyomi/pull/4652#issuecomment-799796122) brought up in the comment:

The problem with having it overflow is basically why I wouldn't want to accept that feature, as it pushes out things for what many would consider noise. I'm also hesitant to actually merge in random sorting since it's a bit awkward and sort of a janky workaround for addressing the actual request of opening up something random.

I think at best, I'd prefer to have an optional [FAB](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) in the library view to open something random from the already filtered library.

**Comment by Vesnyx** [comment]
I definitely don't like the idea of adding in the random sort as well. It seems kind of unnecessary when having a button for it works just as well. 

I am more partial to having a) a button to open a random chapter/manga and b) having a random playlist while reading ( e.g. reading chapter 32 of manga 1 loads chapter 50 of manga 2)

**Comment by pikatwinky** [comment]
Im wondering when this feature will be implemented? I think is a really usefull functionality. 
Is it too complicated to not have been implemented in almost 5 years? 
Anybody knows if maybe there is a workaround to achieve this?
