### ISSUE TITLE
Filter by tracking service in My Library

### ISSUE THREAD

**Issue by wopian** [tachiyomiorg/tachiyomi#1255]
Ref: https://github.com/inorichi/tachiyomi/issues/1147#issuecomment-355594571

More of a QoL for large libraries to find manga not linked to a tracking service.

**Comment by PhaZ90771** [comment]
I agree. This is especially the case when you read new manga, since more likely than not, the tracking sites haven't added that series yet.

Currently as a work around I've been tracking series through Google Keep when I start reading a series that hasn't been added to my tracking site yet.

It is **very** difficult to find these series after the fact, since you are forced to navigate through series one by one to track them down.

Even just having the check mark show up in the browse view would be a huge improvement.

**Comment by Bm12347** [comment]
@arkon this should be closed as it is # already implemented
