### ISSUE TITLE
Can not delete chapters of local manga

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#1770]
**App version:** 0.8.0
Android 8.1

Deleting local chapters doesn't work from within the app. You have to go to the local folder in file manager and delete from there.

**Comment by Flamingpineapplepie** [comment]
Strange. I experienced an issue like this myself. All I needed to do was close the application and reopen it. Another time i  reboot my phone and checked the chapters to find the read chapters (which are set to delete) were no longer downloaded. Also, did you try clearing your cache first? Did you also hold down on a chapter and select multiple ones before attempting to delete them? Provide some more details if possible? Your post is really lacking in how you experienced this problem and what you tried to do to delete the chapters.

**Comment by yambadr** [comment]
Did you actually read what I wrote? The issue happens with "Local manga" not downloaded manga.

**Comment by udf** [comment]
This was bugging me, so I decided to take a look at it.

[`DownloadManager.deleteChapters`](https://github.com/inorichi/tachiyomi/blob/6586c4e387fb74859aa129046a4377fcdedbc043/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt#L167) ends up calling [`DownloadProvider.findSourceDir`](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt#L64).

There are two problems that cause this bug:

1. `findSourceDir` only searches the downloads directory, which is usually not `/sdcard/Tachiyomi`.
1. `findSourceDir` uses [`getSourceDirName`](https://github.com/inorichi/tachiyomi/blob/6586c4e387fb74859aa129046a4377fcdedbc043/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt#L108), which just calls `.toString()` on the source. This is incorrect since it ends up looking for a directory called "Local manga"* instead of "local".

*This is [taken from the resources](https://github.com/inorichi/tachiyomi/blob/6586c4e387fb74859aa129046a4377fcdedbc043/app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt#L68).

`#1` could be fixed by also searching `/sdcard/Tachiyomi` if searching the downloads directory fails.  
`#2` could be fixed by making the `Source` interface expose a url, like how [`SManga`](https://github.com/inorichi/tachiyomi/blob/043e3784e8b5e14b2a37cbe5f58801ce098f888d/app/src/main/java/eu/kanade/tachiyomi/source/model/SManga.kt#L5) (parent of [`Manga`](https://github.com/inorichi/tachiyomi/blob/043e3784e8b5e14b2a37cbe5f58801ce098f888d/app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt#L5)) and [`SChapter`](https://github.com/inorichi/tachiyomi/blob/043e3784e8b5e14b2a37cbe5f58801ce098f888d/app/src/main/java/eu/kanade/tachiyomi/source/model/SChapter.kt#L7) (parent of [`Chapter`](https://github.com/inorichi/tachiyomi/blob/043e3784e8b5e14b2a37cbe5f58801ce098f888d/app/src/main/java/eu/kanade/tachiyomi/data/database/models/Chapter.kt#L6)) do. But while we're doing that, having a method on a source to get its directory might be easier.

However, adding a field to `Source` might not be possible because of extensions (I assume they have to implement `Source`, so changing `Source` would break them). In that case, adding a special case to `findSourceDir` when `source` is a `LocalSource` would be the better option. We'd need to add a method to `LocalSource` that returns the directory path since [it's currently hardcoded to be "local"](https://github.com/inorichi/tachiyomi/blob/6586c4e387fb74859aa129046a4377fcdedbc043/app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt#L58).

**Comment by joseph619** [comment]
@udf  Can you please submit a PR to fix this?

**Comment by udf** [comment]
@joseph619 Done

**Comment by joseph619** [comment]
Seems like this issue still persists for some users

**Comment by Guillaume-Garrigos** [comment]
I am facing the same issue.

**Comment by KGTasa** [comment]
I am having the same problem on Tachi 0.8.5 (I'm using the older version since my tablet is 4.4.4). What is the fix for it?

**Comment by arkon** [comment]
We don't provide support for old versions, but the way to delete things has always been to just delete it from a file manager app.

**Comment by B10Reaper** [comment]
So is there a way to do it manually while we wait for the fix? The issue still exists in the latest update, I've got multiple entries in my local source that don't exist on the card anymore.

**Comment by KGTasa** [comment]
Hey, my problem was that when I put manga on a card, it also made a folder with the name of the manga on the internal storage, so when you delete it from the SD card, also look delete the folder with the name of that manga on the internal storage, and that will get it out of your library. Hope this helps.

**Comment by B10Reaper** [comment]
Hi,
I may have a different problem if that's the case, because I deleted the file folders from the Local folder and they won't disappear from my Local source in the app. 
Folders, files, all gone but the manga remains in the app. Not sure how to clear that.

**Comment by joseph619** [comment]
Remove the local manga from library, then clear database. Also ask for help on Discord.

**Comment by B10Reaper** [comment]
Did that, cleared cache and database, it's still there. Not sure what else to do with it if it's not gonna work properly and nobody is going to fix it after 4 years.
I don't use discord, that's why I'm in a bug thread.

**Comment by KGTasa** [comment]
Download Discord, it's free and easy to use. Someone will help you there much faster then in a Github bug thread.

**Comment by B10Reaper** [comment]
No thank you, I don't appreciate spyware on my computers. 
It's not a huge issue, just a weirdly overlooked one, considering how active the development is I just think it's strange it still exists and wanted to see if anyone had found a fix so far. If it comes down to it I'll ignore them until the fix is implemented.

**Comment by arkon** [comment]
App explicitly doesn't allow deletion of local content nowadays to avoid unintentional data loss.
