### ISSUE TITLE
[Feature Request]Batch download and custom folder features

### ISSUE THREAD

**Issue by ybhgl** [tachiyomiorg/tachiyomi#1846]
Dear Developer, can you add a function of downloading cartoons in batches (multiple choices) on the bookshelf page? Every time I click on the cover of the book to download, it's so inefficient. In addition, can you add a user's own choice whether to create the chapters folder function, most cartoon sites click into the cover of the cartoon is not divided into chapters, now the software automatically create the chapters folder too much. Now the file situation: site - cartoon name file - Chapter - cartoon original document (4 steps), the desired effect: site - cartoon name file - cartoon original document (3 steps) Thank you very much!

p.s:My English is not so well, please forgive!

**Comment by CarlosEsco** [comment]
What source are you using that it's not chapter based?

**Comment by ybhgl** [comment]
NHentai

**Comment by ybhgl** [comment]
> What source are you using that it's not chapter based?

NHentai

**Comment by Efreak** [comment]
Tapastic does this too. Many "chapters" on tapastic are just single pages, since webcomics tend to only put out one page at a time.

**Comment by arkon** [comment]
Can already download unread chapters from the library screen.

**Comment by Efreak** [comment]
@arkon the problem isn't downloading unread chapters, the problem is creating a folder for each chapter when there's only a single page per chapter, it makes organization difficult for long webcomics (4000+ "chapters") and slow storage/sdcard if there's two files per page instead of just one. I get around this with a termux command `rename 's/(chapter [0-9]+)\//\1/' chapter\ */*`, but that's not helpful if you don't know about that or don't have termux/other cli installed. With some protocols/devices, having twice as many files can more than double the time the transfer takes.

**Comment by arkon** [comment]
That's not quite what the original issue was asking for. Please create a new issue to request for saving things as archives if your issue is wanting less files.
