### ISSUE TITLE
URL Encoding in requests

### ISSUE THREAD

**Issue by FoxInFlame** [tachiyomiorg/tachiyomi#2028]
**App version:**
v0.8.4

**Android version:**
7.0

**Issue/Request:**
This is an issue I encountered while trying to make an extension. When `.setUrlWithoutDomain()` is called with a string that contains URL encoded characters, it seems as though the requests are being sent by Tachiyomi using decoded characters.

e.g. If `.setUrlWithoutDomain("/%E3%83%86%E3%82%B9%E3%83%88")` is called, it sends a request to `/テスト`, which is different from `/%E3%83%86%E3%82%B9%E3%83%88`. The most obvious example is when using hashtags, which when decoded no longer become part of the URL.

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**
I couldn't get Fiddler to work with Tachiyomi, so I'm not sure if this is an issue related to Tachiyomi or with my phone's caching system, but I believe it is with Tachiyomi's way of handling URLs.

**Comment by FoxInFlame** [comment]
Still having this issue. Makes it hard to develop extensions.

**Comment by arkon** [comment]
It's been a long time since this was opened, but I'm not actually sure why a server should be treating `/%E3%83%86%E3%82%B9%E3%83%88` and `/テスト` differently, especially when some browsers automatically encode/decode things anyway.

I don't think any other devs have brought this up in the last 2 years either, so I'm not sure how common of an issue this is.
