### ISSUE TITLE
[feature request] adjust CONTRAST

### ISSUE THREAD

**Issue by orangpelupa** [tachiyomiorg/tachiyomi#2083]
Currently tachiyomi allows brightness adjustment.
It would be awesome if it also have contrast adjustment. Even better if it have automatic level adjustment. 

Because many scans have bad contrast. And some kind of contrast adjustment will be great, even if it's manual adjustment

Thankyou

**Comment by CarlosEsco** [comment]
Adjust the color mode in dev. Burn in should make it darker

**Comment by orangpelupa** [comment]
Sorry, what do you mean in dev?

Developer option in android settings? 

On my inkbook explore with android 4.4 there were no "color mode" option.

**Comment by CarlosEsco** [comment]
If you are on the developer version of tachiyomi. If not then you have to wait for a new release

**Comment by orangpelupa** [comment]
Thanks a ton for the info! I'm not on the dev release channel. Will patiently wait

**Comment by orangpelupa** [comment]
Tied dev 1515. I can't find this "burn in" option :(

Where is color mode? 

I only found color filter blend mode: default, multiply, screen

**Comment by Flat** [comment]
![Screenshot_20190615-211730_1](https://user-images.githubusercontent.com/2048861/59557880-31dd1080-8fb3-11e9-9d9b-d8c338025a03.jpg)

**Comment by orangpelupa** [comment]
Sorry its nowhere on my r1515 tachiyomi

https://imgur.com/a/piCv0ed

**Comment by CarlosEsco** [comment]
your device is too old then..   https://github.com/inorichi/tachiyomi/pull/2013

you can leave the ticket open but i doubt something like this will be added since on newer devices color mode supports all options

**Comment by orangpelupa** [comment]
Ah I see. Thank you for the info. I'll keep this open, for a rare chance someone can dev it to work on older android.

**Comment by Deumiankio** [comment]
As stated in the PR linked by CarlosEsco some of the color blend options are not enabled on older devices because they are not supported by older Android APIs (I tested this on the emulator while rewriting the color filter code).

I do not remember if other blend modes would work an older Android versions with hardware acceleration of the main reader view disabled, but since that would slow down the reader app and make for a worse user experience (i.e. longer loading times, higher battery usage, choppy scrolling and animations) I doubt it will ever be a viable option to add into the release version.

You seem to be using a device with an E-Ink display where I assume you disabled animations and scroll one page at a time, which could migitate against some of the problems of disabling hardware acceleration but not all of them.

**Comment by orangpelupa** [comment]
You re right. I use inkbook explore eink reader and disabled all animation on tachiyomi.

the "side menu" animation can't be disabled tho.

Anyway, the eink screen is already Uber slow in refreshing the display hahaha

**Comment by arkon** [comment]
No intention to support anything special for older devices.
