### ISSUE TITLE
[Feature Request] Add search, sort and enable/disable toggle for Sources 

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi#2519]
The follow features for Source menu is already available on J2k, it will add:

1. Search function for Source page similar to that for Extensions.

2. Sorting, ie sources will grouped by enabled and disabled, with enabled sources on top.

3. Toggle to enable/disable all sources. (If somebody uninstalls and reinstalled Tachi now, all sources are enabled by default and it's a huge pain to disable all of them manually, I had to disable over 70 sources one by one when I installed this fork)

Link: https://github.com/Jays2Kings/tachiyomiJ2K/issues/12

**Comment by alittlebitofit** [comment]
Yes please, I need:
1) Search engine for Extensions.
2) A sorted list of extensions which can be organized categorically, i.e. Manga, Manhwa, etc wise.

Every extension has the tiny description which says `<Language> <Version>` under the `<Extension>` name. But the problem is that the `<Language>` is written in that specific language, for example `Japanese` is written as `日本語` which is in Japanese but I can't read it. So I have a hard time going through searching an extension.

Please add these features.

@joseph619 what do you mean by "Sources", "Source menu" and "Source page" exactly?

**Comment by joseph619** [comment]
@alittlebitofit TachiyomiJ2k is a fork which has the feature mentioned above, alongside many other features.

**Comment by arkon** [comment]
Sort of implemented, albeit differently from J2K. Sources are managed via their extension details instead.

**Comment by joseph619** [comment]
Search for source from Extension detail is still missing, still have to swipe through 100 Madara sources to enable one

**Comment by ghostbear** [comment]
Is this still an issue since sources are split nowadays?

**Comment by arkon** [comment]
I don't have a good answer for that since I obviously never needed it, but I do wonder if the existing redundancy between the sources filter menu and the extensions details is still needed.

**Comment by joseph619** [comment]
> Is this still an issue since sources are split nowadays?

I don't think it's needed anymore, most people only use 5-10 ext at most now so it's very easy to disable/enable sources
