### ISSUE TITLE
[Bug] Random Images Will not Display

### ISSUE THREAD

**Issue by Schezuk** [tachiyomiorg/tachiyomi#2614]
### Device information
* Tachiyomi version: Latest
* Android version: 4

## Steps to reproduce
1. Read from any source of manga online.
2. Some random image, after fully loaded, is blank.
3. Scroll up or down at least 5 pages, then scroll back.
4. Without reloading from the Internet, the proper image displays instantly.

### Other details
1. It happens in Webtoon mode. Other modes are not tested.
2. When scrolling to and fro, images properly displayed previously may disappear as well.
3. Downloaded or local manga is affected.
4. It is estimated that the image is cached already but just does not display.

**Comment by scb261** [comment]
Also happened to me few times. I think it was vertical mode. But for me it was enough to go up and down 1 page, not 5. Not sure how to catch this situation since it's very rare.

**Comment by scb261** [comment]
Finally figured out how to reproduce. Stable 0.9.2.
1. Download a chapter (another way is to scroll page by page so they get cached. I also tried with an undownloaded chapter at all and couldn't reproduce the bug, maybe I tried not enough times)
2. Use the slider to change page. Do it by dragging, don't just tap in a specific point of the slider.

[Here (Google Drive)](https://drive.google.com/folderview?id=14lvlkaguAcSS8Mida-0rbdfg-Yo8NMCG) is an example of the bug.

It's seems that the problem caused by loading too many pages when the slider is dragged and some pages are emitted because of that. But it can also happen with regular reading if I'm not mistaken. I'll update the comment when it happens again.

Some workarounds for users:
- Go up or down at least 2 pages and then return to the 'invisible' page
- Change screen orientation
- Close the chapter and open it again

**Comment by scb261** [comment]
Seems like J2K fixed it, maybe it'll help
https://github.com/Jays2Kings/tachiyomiJ2K/commit/379f27b01ec57a592fed611c9ccfe4727d6e6cfb
https://github.com/Jays2Kings/tachiyomiJ2K/commit/c0eb0b62c7252d1008f0b76362832fe677701973

**Comment by arkon** [comment]
The J2K fixes are due to other changes specific to that fork IIRC.

**Comment by scb261** [comment]
For the record: closed because I can't reproduce it anymore on the last version that supported Android 5, and because the original issue is about Android 4 that was dropped a while ago.
