### ISSUE TITLE
[Feature Request] Three dot to mark Download/Read/Unread chapters

### ISSUE THREAD

**Issue by Akazotik** [tachiyomiorg/tachiyomi#2912]
Please return three dot menu to mark chapters Download/Read/Unread. It's really uncomfortable to make it with longtap

**Comment by Soitora** [comment]
I believe it's the best it can be right now.

However, I think an added "Slide right to toggle read state" and "Slide left to download/delete" would be good for quick actions.

**Comment by Akazotik** [comment]
So three dot like in j2k

**Comment by Soitora** [comment]
To mark all chapters or specific ones?

**Comment by Akazotik** [comment]
three dot on each chapter to mark it

**Comment by Akazotik** [comment]
So. Anything but longtap to download chapters or mark them read/unread

**Comment by asdkant** [comment]
> I believe it's the best it can be right now.
> 
> However, I think an added "Slide right to toggle read state" and "Slide left to download/delete" (alternatively bookmark) would be good for quick actions.

YES, this would be the best usability-wise since (as of now) there's nothing else one would want in a three-dot menu for an item in the chapter list.

**Comment by arkon** [comment]
Sliding isn't going to work as long as keep a tabbed interface, but we'll see if we eventually remove that like J2K.

**Comment by Akazotik** [comment]
> Sliding isn't going to work as long as keep a tabbed interface, but we'll see if we eventually remove that like J2K.

Leave categories with left-right slide, and manga page make like in j2k with download marks and slide to read/unread

**Comment by asdkant** [comment]
Not having the three-dot menu for items in the chapter list is a usability minus for large-screen devices. In my case I have a 10-inch tablet, in the image below you can see the distance I have to move for the three actions (select chapter, tap the delete icon, confirm:
![image](https://user-images.githubusercontent.com/3915542/81013895-5263c280-8e32-11ea-8d02-b11992408fd7.png)

**Comment by Clydefrosch22** [comment]
I agree with that.
I find it especially tedious in the new releases screen.
Longtap, usually somewhere on the top of the screen, move finger all the way to bottom of the screen to do any action (it doesn't help that, since i usually balance my tablet against my stomach, the option menu is often covered with a shirt and it always takes me a moment to remember everything is down there now) and then move it all the way up to the top left to cancel out of the multitap function again
Then doing it all again for deleting the chapter after read.

The three dot menu as it was before was rather comfortable in that i barely had to move my right thumb for downloading.

**Comment by arkon** [comment]
Download icons partially addressed this.

Read/unread or other actions could be addressed by #3630.
