### ISSUE TITLE
Allow different library categories to have different display options

### ISSUE THREAD

**Issue by gattillynx** [tachiyomiorg/tachiyomi#3288]
>  Allow different library categories to have different display options

As it stands, All the categories in the Library can be set to only one kind of display.

so how about an option to have an independent display option for each category? (that can be checked or unchecked depending on preference)

This would allow users to make some categories show up as grid view while others as list view.
Having multiple display options for different categories would enable making reading lists within the app easier. Coupled with adding a 'date added' filter option would make tachiyomi more usable as a reading list+reader app combo.

Here's an image to visualize it better: https://i.imgur.com/DXDB8CS.jpg

**Comment by Rogavactive** [comment]
I would like to work on this

**Comment by scb261** [comment]
There are several issues opened that ask for per-category sort/filter/display, maybe they should be combined in one issue (I guess this one, since there is open PR)?
#3288 (this one) and linked PR - display mode
#2698 - filter/sort (I'm not exactly sure what the author wanted here)
#3722 - filter/sort

I think the option should allow user to select what he wants to be per-category and what global (for example user wants display mode to be global for all categories, but filter/sort per category).

Note that the PR linked above implementing only display mode and won't close all those issues. If it will be merged, then it is possible that rewrite would be needed later to implement fliter/sort as well (bit I'm not expert to say it for sure).

**Comment by paulo27ms** [comment]
Implemented in https://github.com/tachiyomiorg/tachiyomi/pull/5232
