### ISSUE TITLE
[Feature Request] <please update hidden function>

### ISSUE THREAD

**Issue by Noname-noragami** [tachiyomiorg/tachiyomi#3317]
### What/Requirements
1.Add hide history, new chap, newly add or every thing in recent, library tab for choice category
2.Add hide extension from extension tab
3.Add download , and download new chapter for only selected category

**Comment by SaruDesu** [comment]
Wdym by hide extension? If it is hiding sources then there is already. For preview versions r2373 and older the source hider is in the source filters (the inverted 3 line pyramid in the sources tab in browse); For preview versions since r2402, its in the settings of each downloaded extensions in the extensions tab.

For r2373 and older:
![20200616_104958](https://user-images.githubusercontent.com/51081028/84726775-32422a00-afc0-11ea-911a-a8e3139f6857.jpg)
![20200616_105538](https://user-images.githubusercontent.com/51081028/84726786-38380b00-afc0-11ea-93bf-ec99e4d857ee.jpg)

For r2402 to latest:
![20200616_105058](https://user-images.githubusercontent.com/51081028/84726921-82b98780-afc0-11ea-9bdc-078c88c88a17.png)
![20200616_105230](https://user-images.githubusercontent.com/51081028/84726932-89e09580-afc0-11ea-9cdd-593753f8b4dc.jpg)

**Comment by Noname-noragami** [comment]
But MangaDex in extension still showing setting, not Installing or hiding.
If you can please add download , and download new chapter for only selected category

**Comment by arkon** [comment]
> 1.Add hide history, new chap, newly add or every thing in recent, library tab for choice category

This is hard to understand.

> 2.Add hide extension from extension tab

You didn't provide a reason, so I don't know why this would be a wanted thing.

> 3.Add download , and download new chapter for only selected category

This already exists if you're talking about auto downloads. You can also long press manga in the library to download unread chapters.
