### ISSUE TITLE
[Feature Request] Scrolling should auto-hide controls

### ISSUE THREAD

**Issue by Wiz1991** [tachiyomiorg/tachiyomi#3411]
When reading if you click anywhere on screen controls show up for switching pages and such. If you continue scrolling these controls wont go away, you have to click again to hide them. 

This is breaking immersion  and its quite bothersome, there should be an auto-hide feature, if you continue scrolling it will automatically go away, if you dont do anything it shouldnt go away.

**Comment by CarlosEsco** [comment]
why cant you just click again after you show it?

**Comment by Wiz1991** [comment]
> why cant you just click again after you show it?

Its mostly because it happens so often that it breaks immersion. Id read, swipe swipe then accidentally click on screen while reading. This can happen multiple times and it just so annoying having to click each time, and it makes sense for it to go away when you are reading.

**Comment by CarlosEsco** [comment]
It only shows if you click in the center, just click off center a  bit more and you will never

**Comment by Wiz1991** [comment]
But i scroll in the center

**Comment by curche** [comment]
> But i scroll in the center

Focusing on this, if you prefer to move the Menu option to another part of the screen (rather than the centre), there are now [Navigation Layouts](https://tachiyomi.org/help/guides/reader-settings/#navigation-layout) and in particular the Kindle-ish layout

Navigation Layouts are available in the Latest version of the app, [0.11.1](https://tachiyomi.org/download/)
If this feature request is no longer useful for you, consider closing the issue
