### ISSUE TITLE
[Feature Request] Sort by Author in Library

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#3947]
## Why/User Benefit/User Problem
I have a pretty big library but I want to keep it seperated as official manga, h manga and doujins instead of having 20+ categories to seperate offical, h and doujin into indiviual a - z tabs per author since currently it only sorts by the title of the manga and the other options don't allow for sorting by author, I don't know how easier/difficult this is to add compared to #1803 but it is at least a half step if #1803 is too hard to impliment.

## What/Requirements
Just an option to sort by the author's name as it's listed under the title of the manga alongside other sorting options.
Red arrow points to where the author's name is listed.
![Screenshot_20201017-171352_Tachiyomi](https://user-images.githubusercontent.com/69066429/96329899-dd610e00-109c-11eb-8364-21d1df631101.png)

**Comment by MercerBoi** [comment]
If you simply type the name of the author/artist in the library search bar, all entries are sorted by that artist/author. 
![Screenshot_20201017-190335](https://user-images.githubusercontent.com/28984045/96338424-a6462900-10ab-11eb-9939-5de63cb7c3db.png)

**Comment by bugreportanon** [comment]
I already know you can do that, I want a sort option that I can have always enabled so I don't have to manually search every time.

**Comment by joseph619** [comment]
Sorting will not show where one Author starts and ends, it's the same as sort by Source which was removed since it was useless

**Comment by bugreportanon** [comment]
Sort by source is useless because it just groups by website this is different, chapter releases on PC for h manga is named [group name/author](title) this allows for anyone that keeps them easily sorted alphabetically by author so you can just scroll through and find the manga you're looking for easily. Currently it only sorts by title alphabetically which is useless if you want it grouped by author since one person's work are seperated and you have to either manually search if you remember the author's name or scroll through looking for their artstyle.

This makes #1803 more useful because even if you make sub groups that are sorted alphabetical by author, for example all authors who's name starts with B it groups the works by the author and not the title which makes zero sense. 

Also you can tell where their work starts and ends since the style will be similar to begin with, I have my h manga sorted alphabetically by author on PC and it's a lot more organised than the current options provided in the app.

**Comment by arkon** [comment]
Agreed that this is as useful as sorting by source.
