### ISSUE TITLE
[Feature Request] Reading Modes according orientation

### ISSUE THREAD

**Issue by lucfig** [tachiyomiorg/tachiyomi#4028]
## Why/User Benefit/User Problem

Some users, like myself, have different habits and reading styles according to phone orientation. Personally I set the scale to fit width, so I have a full page on portrait and a zoomed page in landscape.
So I this scenario I always have to scroll down in landscape to read the hull page and it would be intuitive to have a infinite vertical scroll when in landscape. 
With different options for landscape and portrait, I could keep left to right in portrait.

## What/Requirements
Add another menu entry for landscape reading mode.

**Comment by crisalis2** [comment]
I also want separate reading settings for portrait and landscape. I use the continuous vertical reading mode, and in portrait I choose to crop borders for a bigger image, but in landscape I don't crop them because the image is already quite big. Having to change the setting manually each time is tiring.

**Comment by arkon** [comment]
Not quite what was requested, but it's easier to change now with the new(ish) reader shortcut menus.
