### ISSUE TITLE
[Feature Request] [Download and Unread Filter] Both filter turned on

### ISSUE THREAD

**Issue by Jacekun** [tachiyomiorg/tachiyomi#4047]
## Why/User Benefit/User Problem
- For peeps that wanted to Read Manga offline, and see what they have downloaded, that are also unread.

## What/Requirements
- When Download and Unread filter is checked, it would first check if a manga has downloaded chapters. Among the dowloaded chapters, check if there are any Unread. If there are, show it.

As how the current filter works, If both filters are checked: It displays Manga with **Downloaded** chapters, even if that chapter is already *read*.

**Comment by scb261** [comment]
Since others on discord had trouble understanding the request, I'll describe it in my words for anyone who wants to implement this.
#### How it would work
Current filter picks up manga even if one chapter is downloaded and second chaper is unread. New filter would pick up a manga only if it's the same chapter that is unread and downloaded.
#### Why
One of usecases: user has autodownload enabled and updating library, it would be useful to know which manga with new chapters already downloaded. Current filter also shows manga that has older chapters downloaded and new chapters undownloaded (in queue).
#### Other details
The author also mentioned (on discord) a badge that would work the same way - show how many chapters are unread and downloaded at the same time. This would help if user is too lazy to change filter each time (hi, I'm the lazy user that is tired switching tri-state filters), so the user could just enable badge and scroll library to see manga that has unread and downloaded chapters.

**Comment by SnexusG** [comment]
I think it would be better to change the current functionality of how the unread+downloaded filter works when selected together instead of adding another filter that implements this feature separately. If it's okay I would like to work on this.

**Comment by Jacekun** [comment]
> I think it would be better to change the current functionality of how the unread+downloaded filter works when selected together instead of adding another filter that implements this feature separately. If it's okay I would like to work on this.

That is what I meant. So, if 2 options are **checked** together, the filter works in a way, that both conditions are satisfied.
And, feel free to do it. Since, my laptop can't handle Android Studio. I'm trying to find a lightweight alternative, besides notepad and android sdk.

**Comment by arkon** [comment]
I'm pretty sure there's going to be people who are used to the current behaviour who will not be happy with this change.

My other thought is that the "Completed" filter isn't specific to individual chapters, so having downloaded/unread being specific to individual chapters feels a bit counter-intuitive.

**Comment by Jacekun** [comment]
> I'm pretty sure there's going to be people who are used to the current behaviour who will not be happy with this change.

In that case, it can be made into a separate filter. So, an additional filter that works as **AND**, rather than **OR** (Which is how it is right now).

> My other thought is that the "Completed" filter isn't specific to individual chapters, so having downloaded/unread being specific to individual chapters feels a bit counter-intuitive.

I don't get why this new filter would affect **'COMPLETED'** filter. This **'Completed'** filter depends on the status of the manga, as far as I can tell. The **new* filter isn't basing on that. Rather, it takes note of what **downloaded** chapters are **unread**.


The way I can see this achieved is:

* Use the current **Download** filter as base, to check which manga has downloaded chapters.
* Then, perform another filter to check among those downloaded chapters which are unread.

**Comment by SnexusG** [comment]
> I don't get why this new filter would affect **'COMPLETED'** filter. This **'Completed'** filter depends on the status of the manga, as far as I can tell. The *_new_ filter isn't basing on that. Rather, it takes note of what **downloaded** chapters are **unread**.

I think they meant that the way Completed filter doesn't apply to individual chapters but instead applies to the whole manga, the downloaded/unread filter also does the same as of now

**Comment by Jacekun** [comment]
> I think they meant that the way Completed filter doesn't apply to individual chapters but instead applies to the whole manga, the downloaded/unread filter also does the same as of now

Which is why I said this can be done as a separate (it's own) filter. That would make the current filter work as usual.

**Comment by Jacekun** [comment]
Turns out, there's a "Downloaded Only" mode toggle on Tachiyomi which would make this request irrelevant. 

The toggle works as I wished in this request (shows only chapters that are downloaded) so I'm closing this issue now.
