### ISSUE TITLE
[Bug] Stuck in LIbrary.

### ISSUE THREAD

**Issue by mrdroops** [tachiyomiorg/tachiyomi#4143]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 9
* Device: Samsung Galaxy J7 Pro

## Steps to reproduce
I don't know how to reproduce this bug, I suspect it occurs when I update, migrate or activate biometrics as security, or something else.

### Expected behavior
When I open the application it appears my mangas normally.

### Actual behavior
[EN]
It gets stuck in the Library tab, no manga appears, when I go to the More tab, and I try to open the Library or Downloads option, the application crashes, I can't go back to the previous tabs, just closing the application, this bug has been happening. time, but after the last updates is happening more often, I try to restart my phone, clear the cache and nothing works, but after a while it will start working out of nowhere.

[PT]
Fica travado na aba Biblioteca, não aparece nenhum manga, quando vou para a Aba Mais, e tento abrir a opção Biblioteca ou Downloads, o aplicativo trava, não consigo voltar para as abas anteriores, somente fechando o aplicativo, esse bug vem acontecendo tem um tempo, mas depois das últimas atualizações está acontecendo com mais frequëncia, eu tento reiniciar meu celular, limpar o cache e nada funciona, porém depois de um tempo ele volta a funcionar do nada.
![Stuck_1](https://user-images.githubusercontent.com/40572302/102249828-8c756680-3ee1-11eb-9ce8-521197a06a5f.jpg)
![Stuck_2](https://user-images.githubusercontent.com/40572302/102249884-9dbe7300-3ee1-11eb-826c-e02704f2e33a.jpg)

**Comment by Im1not2your3toy** [comment]
I think I have the same issue even though it might look slightly different

## Device information
App version: 0.10.7 (standard, c87ba62, 53)
Android version: 10 (SDK 29)
Android build ID: QKQ1.190910.002 V12.0.1.0.QFGMIXM
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: lavender
Device model: Redmi Note 7
Device product name: lavender

## Steps to reproduce
1. First step
Launch the app
2. Second step
Initiate updating library. Tried both ways - pulling down "updates" page and pressing "refresh" button.

### Expected behavior
Updating library starts, after some time a notification with a list of updated chapters appears.

### Actual behavior
The updating process starts, you can see the progress bar getting a little blue but then it just stops. No error notification, nothing appears.

## Other details
This issue occurred two days ago after updating to the latest version. Tried clearing cookies and installing latest app version from the official site

**Comment by Im1not2your3toy** [comment]
Updating today extentions Madara (multiple sources) and manhuascan didn't change anything

**Comment by mrdroops** [comment]
Update: After I created this issue, I decided to uninstall the app and all installed extensions and download version 0.10.5, updated the app without my library and installed all the extensions. Right after, I started to restore my BackUp, until now I didn't have any problem. Therefore, I ask you to close this Issue. In case I have the same type of problem I will create another one referencing this.
