### ISSUE TITLE
Problem with install 0.10.7

### ISSUE THREAD

**Issue by penrose72** [tachiyomiorg/tachiyomi#4154]
## Device information
* Tachiyomi version: 0.10.5 0.10.7
* Android version: 10
* Device: Samsung Note 9

## Steps to reproduce
1. Try to install new version

## Issue/Request
If I try to install 0.10.5 it's work. But if a try to install 0.10.7 at the end of jnstallation process I receive an error.
I tried to install after remove the previusly version, but nothing change.
If I try to reinstall 0.10.5 all work without problem
Usualy I install Tachiyomi within fdroid. But fdroid install only 0.10.5

## Other details
Additional details and attachments.

**Comment by AriaMoradi** [comment]
download and install adb on your pc, enable developer options on your phone, turn on usb debugging,
download tachi apk on your pc,
open the directory that contains the downloaded apk in commandline, input `adb install <name of apk>` and give us the error that it shows you.

**Comment by scb261** [comment]
The problem is fdroid, they build the app with their own signature. [Create backup](https://tachiyomi.org/help/guides/creating-backups/#creating-backups), uninstall the app, download from github or [the site](https://tachiyomi.org/download/), install, restore. Or wait until fdroid releases the new version

**Comment by arkon** [comment]
Follow what @scb261 said.
