### ISSUE TITLE
[Bug] Tap navigation in reader is inverted without invert tap enabled

### ISSUE THREAD

**Issue by dafillio** [tachiyomiorg/tachiyomi#4237]
---

## Device information
* Tachiyomi version: r2959
* Android version: 10
* Device: Mi Mix 2

## Steps to reproduce
1. Set reader from left to right (or other views, I think they're all messed up).
2. Turn invert tap setting to none
3. Tap on right side of screen in reader

### Expected behavior
You should advance to the next page

### Actual behavior
It goes back a page

## Other details
I believe this affects all reader view settings, I've tried webtoon, left to right, and right to left personally. It seems like the default behaviour is now inverted. This might also affect other types of navigation but I don't use them personally. This behaviour is the opposite of what was default as of the previous build version

**Comment by ghostbear** [comment]
The way tapping works has been changed and the default for Right to Left and Left to Right is
```
+---+---+---+
| N | M | P |   P: Previous
+---+---+---+
| N | M | P |   M: Menu
+---+---+---+
| N | M | P |   N: Next
+---+---+---+
```
I was thinking if the user doesn't like to change to the next page on the left side they can invert it to the right side

---

For what doesn't match the previous build
- Right to Left: Matches previous
- Left to Right: Inverted
- Webtoon: Inverted
- Vertical: Inverted
- Continous vertical: Inverted

For Webtoon, Vertical, and Continuous vertical I will fix them. 
For Right to Left and Left to Right, I'm unsure if adding separate default navigation for Left to Right will help due to them both having the same invert. Like I said before
> I was thinking if the user doesn't like to change to the next page on the left side they can invert it to the right side

**Comment by dafillio** [comment]
Hmm I guess as long as the inverted option exists it's not a big deal but it seems a bit odd to have the default behaviour for left to right to proceed to the next page be on the left side. To me it would make more sense to have the default behaviour be that you would tap on the side in which you want to progress/turn towards. As long as this is expected behaviour that's fine it just seemed odd enough that I thought it was a bug and warranted a report. I strongly agree on reverting the vertical changes though, that ones seems to be a little more clear cut.

**Comment by Matth7878** [comment]
Can't wait for this to be fixed. It's really annoying to not be able to tap right to go next on left right flow.
At least with webtoon mode there is the ability to invert tapping but for left to right and right to left the setting is shared. :-/
