### ISSUE TITLE
[Feature Request] Too Many Push Notifications

### ISSUE THREAD

**Issue by Lindsor** [tachiyomiorg/tachiyomi#4257]
## Why/User Benefit/User Problem

Its very annoying to receive hundreds of push notifications/phone vibrations when chapters are being downloaded. It adds no value to the user and only provides annoyance.

## What/Requirements
Currently when the app downloads new chapters onto the device 1 push notification is sent out per chapter page.
If you are tracking many manga this can cause upwards of a hundred pages to be downloaded.
Every single one of those pages will trigger a push notification and make the phone ring/vibrate unnecessarily.

There should be an option to control how the notifications work.
1. Current behavior
2. Only send ONE notification which says: "Updating mangas: X, Y, Z, ..." or something like that. Then ONE notification saying "Done updating mangas: X, Y, Z". or something like that.

The user receives the same amount of value since they know all the mangas updated without the hundreds of unnecessary notifications.

**Comment by arkon** [comment]
- They're "normal" notifications, not push notifications. This app has no push notifications as we have no servers.
- You should be able to just turn off vibrations for that notification channel in the Android settings.
- It's vibrating multiple times because the progress is being updated, for obvious reasons.

**Comment by CarlosEsco** [comment]
What phone do you have?  What you are describing is not the normal behavior
