### ISSUE TITLE
[Bug] Download complete notification appearing randomly

### ISSUE THREAD

**Issue by Elecktronnick** [tachiyomiorg/tachiyomi#4309]
## Device information
* Tachiyomi version: preview r3013 
* Android version: 10
* Device: Redmi Note 7

## Steps to reproduce
1. Delete downloaded chapter
2. End chapter

### Expected behavior
Nothing, just usual chapter deletion or mark that chapter is read

### Actual behavior
Chapter is deleted and marked as read, but also pop up "Download complete"(don't know how it written in eng version) alert, but i didn't download anything

**Comment by kai000bubbles** [comment]
Yeah I also get that since I updated the app but also before that when I want to delete alot of chapters for e.g I have a manga that has 200 chapters I select them all and hit delete..... nothing happens? I don't know why they got rid of the downloaded this on the side of the chapters and put a stupid tick on the side? Now I just have to delete chapters individually which is going to be a pain on some mangas that I have 500+ chapters downloaded and also sometimes it crashes when I go to load a manga chapters tooo even if I have downloaded it.

**Comment by scb261** [comment]
@kai000bubbles tick has nothing to do with mass deletion. You don't see them as deleted because deleting 500 chapters takes time. Also sometimes the app doesn't update downloaded status until you reopen manga. You can also use a file manager, they usually show progress of deletion.

As for the crash - make sure you have latest app, extensions and WebView and create separate issue with attached logcat, since it seems to have nothing to do with the *Download complete* notification bug. Also, if you don't like to encounter bugs and report them properly - use stable version, it has smaller chance to have bugs. Potential ways of getting logcat:
- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

**Comment by Aedyrn** [comment]
Can confirm it happens on android 5.0 with r3013. In addition I can see the same behavior when I finish any chapter even if not downloaded previously.

**Comment by kai000bubbles** [comment]
> @kai000bubbles tick has nothing to do with mass deletion. You don't see them as deleted because deleting 500 chapters takes time. Also sometimes the app doesn't update downloaded status until you reopen manga. You can also use a file manager, they usually show progress of deletion.
> 
> As for the crash - make sure you have latest [app](https://tachiyomi.org/download/), extensions and [WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) and create separate issue with attached logcat, since it seems to have nothing to do with the _Download complete_ notification bug. Also, if you don't like to encounter bugs and report them properly - use stable version, it has smaller chance to have bugs. Potential ways of getting logcat:
> 
> * https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
> * https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA
> 
> If you have questions - refer to [Tachiyomi Discord](https://discord.gg/tachiyomi)

Deleteing 500 chapters takes time? When before it happened instantly, even Deleteing 2 or 3 chapters takes time, I now have to spam delete chapter now instead of just hitting delete once?

**Comment by arkon** [comment]
The long press menu is still there and functions the same as before. If it's not working correctly, open a separate issue instead of this one that isn't related.

**Comment by SureThingDeiv** [comment]
Having the same issue.
Tachiyomi version: preview r3013
Android version: 10
Device: Samsung S10e

**Comment by Elecktronnick** [comment]
@arkon I found strange condition to this bug. Afaik it shows on these mangas where i at least once downloaded at least one chapter. And it doesn't matter if a chapter is downloaded or isn't right now. And it works with "delete chapters after reading" option. If i disable it, this bug disappears

**Comment by arkon** [comment]
I'm aware of why it happens, no need to dig more into it. Thanks though.

**Comment by Elecktronnick** [comment]
@arkon Oh ok. I've just noticed that title has "randomly" in it, but in my experience it isn't! Great that you know what's the problem!
