### ISSUE TITLE
[Feature Request] Plugin/Add-ons 

### ISSUE THREAD

**Issue by Bexa2** [tachiyomiorg/tachiyomi#4372]
Wouldn't it be if people could be able to code X functionality as a separate apk like with the extensions and users were able to download these plugins?

Maybe the most downloaded or voted plugins could be considered for implementation on the main app.

I just thought of this because I was thinking on the feature requests on here "Save a specific filtered search" and "force webtoon mode if 'long strip' or 'webtoon' tags are present"

They're not requests that would be considered a priority so maybe someone else could work on them with this plugin system.

**Comment by arkon** [comment]
Creating and maintaining a plugin API would be much more complicated than just implementing the features directly.

**Comment by Bexa2** [comment]
Yeah I assumed this was either straight up impossible to implement or very difficult, if it is possible though it would be a case of working hard at the beginning and then leave it to other people to code features.

But I guess that would be the same as pull requests.

**Comment by arkon** [comment]
You'd have to really plan it out to be open ended enough to actually be able to have plugins that can do all sorts of different things. 

Extensions are already limited by the existing API and involves some crafty workarounds to do certain things given those limitations. 

At most, you can have a plugin system for subsets of functionalities like sources or trackers, but anything else should really just be added directly since there'd be no benefit to the user otherwise.
