### ISSUE TITLE
[Bug] Chapters with a single page aren't marked as read properly

### ISSUE THREAD

**Issue by arma26** [tachiyomiorg/tachiyomi#4376]
## Device information
* Tachiyomi version: 0.10.7
* Android version: 11
* Device: oneplus 8 pro

## Steps to reproduce
1. Install XKCD plugin
2. open the latest chapter
3. hit back without scrolling

### Expected behavior
Chapter should be marked as read

### Actual behavior
Read status will not change unless you scroll up to the previous chapter then back down till you reach the limit.

## Other details
I'm using the continuous vertical reading mode.
I'm not sure if this is limited to chapters that have a single page, or whether multiple pages can fit on the screen without needing to scroll.

**Comment by curche** [comment]
This is not a bug in case of xkcd comics and is expected behavior.
This is because each xkcd comic has 2 pages when viewing in tachiyomi:
 1. the comic as an image
 2. the alt-text as an image (basically a hack which uses https://fakeimg.pl to show text as png)
 
Refer:
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/050636f172aabfdb55e92b6e28d9da63345c6381/src/en/xkcd/src/eu/kanade/tachiyomi/extension/en/xkcd/Xkcd.kt#L70-73

When you do the steps as described in Steps to Reproduce, you are only reading the first page (1/2) and hence the chapters hasn't been read completely and so, read status will not be changed
