### ISSUE TITLE
[Bug] Right and left reader navigation mode not selectable as default

### ISSUE THREAD

**Issue by Dauntst** [tachiyomiorg/tachiyomi#4487]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10 (SDK 29)
* Device: Xiaomi Redmi Note 8 Pro

## Steps to reproduce
1. More → Settings → Reader
2. After checking Navigation → Tapping, Navigation Layout will be selectable for Paged and Webtoon.
3. Option Right and Left non-existant.

### Expected behavior
New Right and Left navigation mode selectable as default.

### Actual behavior
Option not there

## Other details
Right and Left navigation is selectable during reader mode. But then you'd have to change it for every single manga.

**Comment by ghostbear** [comment]
I don't know what you mean by "as default" because the `Default` option in navigation mode refers to the old way you navigated with tapping. And you can only set it for all series (one for Pager and one for Webtoon) there is not a per series setting. So if you change it in the reader it will change for all series using the Pager or Webtoon


But yes `Right and left` is missing as an option from the settings
