### ISSUE TITLE
[Bug] Changing the chapter order doesn't change the "Start" position

### ISSUE THREAD

**Issue by ebarruel** [tachiyomiorg/tachiyomi#4495]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10.3.8
* Device: OnePlus 7 Pro

## Steps to reproduce
1. Reorder chapters so that a different unread chapter is next (logically)
2. Press the *Start* button

e.g.
- Chapter 1 is unread and either at the top or bottom of the list (depending on ascending or descending order)
- Reorder the chapters so that Chapter 25 is the first unread chapter at either the top or bottom

### Expected behavior
Ideally, from the example, Chapter 25 should be the chapter opened by *Start*.

### Actual behavior
*Start* continues to open the next chapter using the original order. (So from the example, it continues to open Chapter 1 no matter what order the chapters are in.)

## Other details
I imagine this is very low priority, and it's also very specific. I didn't notice this behavior until I tried to read a title from a source whose chapters showed up in a nonsensical order in the extension. (The title is Hanikamu Honey in the Chibi Manga extension. I thought about reporting it as a bug in the extension, but to be honest it only shows up in this one title, and it's because the site itself orders the chapters differently than all the other titles I checked.)

**Comment by Omar-AbdulAzeez** [comment]
I honestly don't see this as a bug in the app
For a start you can't re-order the manga chapters as you please there is only ascending or descending... and obviously no one would read a manga from the last released chapter to the first released

And obviously its not a bug in the extension since you said the site itself orders it that way

If it's me I'd just change to another source or ask the site itself to change the order

**Comment by Riztard** [comment]
or request extension to reverse the order

**Comment by ebarruel** [comment]
oh oops, just saw this. i see, thank you.
