### ISSUE TITLE
Kanji/Kana Manga titles not showing in the Updates pane

### ISSUE THREAD

**Issue by futsuriai** [tachiyomiorg/tachiyomi#4576]
## Device information
* Tachiyomi version: 0.10.9
* Android version: 11
* Device: Pixel 4 XL

## Steps to reproduce
1. Use a source with manga titles written in kanji/kana, e.g. Manga1000 (JA) : かぐや様は告らせたい (Raw - Free)
2. Wait for a new chapter to be released
3. On refreshing sources the update will display in the notification pane specifying the manga has a new chapter but on the Updates screen the chapter will not show up meaning you have to either navigate to it via the notification or by looking up the manga in your library.

## Issue/Request
Chapters with non-roman names should show in the Updates list.

## Other details
I'm not 100% sure if this is due to the extension but since it correctly showed on the notification that a new chapter was available and in the manga's own "page" I figured it's more likely Tachiyomi itself.

**Comment by scb261** [comment]
Closed issue with the same problem #2089, but it's not always solvable on the extension level as said in the closed issue, since not all sites have date. 

It's actually weird behavior, since chapters in `Updates` are shown with the date they were updated by user, not by source.

**Comment by scb261** [comment]
I'm not sure why it was closed, but I decided to look into it myself since I noticed there is already fetch date and it's already used in the Updates screen.

As far as I can see, this query only used for the Updates screen
https://github.com/tachiyomiorg/tachiyomi/blob/931efed7844d95747cac5a77f07093c710e320c0/app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt#L37-L45
2 things that I would like to notice here:
- it filters by date upload is maximum 3 months old (see below) and sorts by date upload, this will filter out chapters that, I guess, set to 0 when upload date isn't set by an extension
https://github.com/tachiyomiorg/tachiyomi/blob/7a373fb43a2d3f736c032d88b31a4a3bffd8dc5b/app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesPresenter.kt#L72-L77
- it sorts by date upload

But, on upload screen (again, as far as I can see, it's the only place where the query is used) it sorts ang groups them by fetch date
https://github.com/tachiyomiorg/tachiyomi/blob/7a373fb43a2d3f736c032d88b31a4a3bffd8dc5b/app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesPresenter.kt#L79-L89

So, if I'm not mistaken, it can be easily fixed by editing only the query to use fetch date instead of upload date.

**Comment by arkon** [comment]
@scb261 Do you mind either creating a separate more appropriately named issue, or submitting a PR? The kanji/kana part in this issue isn't really the correct thing to be marked as a bug.
