### ISSUE TITLE
[Feature Request] Always same direction Force Portrait

### ISSUE THREAD

**Issue by snan** [tachiyomiorg/tachiyomi#4618]
I wonder if there is a way to always get the the same direction in force portrait rotation.  
As in, if I turn the tablet upside down the picture should not rotate. Sorta like ConnectBot where down always is down.

**Comment by s0alqasim1d** [comment]
@arkon is it possible to further modify this so that sensor disabling is optional?

I still use a preview version before this commit because I like to have force landscape and when I'm laying down and reading with one hand, if it got tired I switch to the other and flip it so I don't touch the buttons by accident.

One other case is if the phone needs charging and I'm still on it reading, I flip it so my hand is on the side with no cable sticking out, without the need to change to free-form mode or toggling auto-rotate.

Thanks for your time.

**Comment by arkon** [comment]
The general "Lock" orientation mode still locks it to whatever orientation you're in with sensors enabled.

**Comment by s0alqasim1d** [comment]
> The general "Lock" orientation mode still locks it to whatever orientation you're in with sensors enabled.

I see, I didn't know about that. But that needs me to be browsing in landscape so that It locks as landscape. My phone is long rather than wide so browsing in landscape is not fun. But reading in landscape helps me enjoy HQ images (I like to see details).

I also happen to have auto-rotate disabled all the time because I don't like many apps in landscape (e.g. YouTube).

Before this commit I could browse in portrait and read in landscape. The "lock" mode is nice but not as flexible as before. Is this "flexibility" worthy of further change?

**Comment by arkon** [comment]
Please open a new issue.

**Comment by snan** [comment]
This is a great feature, thank you arkon
