### ISSUE TITLE
[Feature Request] Overlay on completed manga.

### ISSUE THREAD

**Issue by Jirubizu** [tachiyomiorg/tachiyomi#4662]
## Why/User Benefit/User Problem
This would allow users who browse catalogs or their own library to see which manga is completed or not allowing them to decide if they want to start reading an on going manga or not.

## What/Requirements
A simple green outline or a light overlay would be perfect. I think an outline around the cards in the catelogs would be perfect as it would be more subtle. This can either be done through existing manga sources which provide completion state or you can use a different manga database that provides this info.

**Comment by curche** [comment]
Related to #4654 which was already rejected

You can use filters and/or create categories

**Comment by arkon** [comment]
I think this is actually talking about when browsing sources, but this isn't really possible unless you've either already opened up the manga before or we make an additional request for every single entry to get that data -- which isn't going to happen since it'd be terribly for performance and would likely just make sources unhappy.
