### ISSUE TITLE
[Feature Request] Add support for AVIF images

### ISSUE THREAD

**Issue by ccvelandres** [tachiyomiorg/tachiyomi#4756]
## Why/User Benefit/User Problem

AVIF is the latest image format better than jpeg. I can open avif images normally in firefox, chrome in android 11. 
Currently, when opening AVIF images (via local), the reader displays "The image couldn't be loaded".

## What/Requirements

Add support for avif images and display AVIF images normally like jpeg, etc.

**Comment by inorichi** [comment]
I've managed to compile libavif for Android. It wasn't easy because there's not built-in decoder and you have to pull an additional dependency yourself.

That said, the decoder API of AVIF is sadly very basic. You can't decode to RGB565, decode a smaller region or lower (subsample) the resolution of the image. And the worst part is that there's no way to decode the image row by row. That will make the decoder quite inefficient, as I'll need two buffers containing the full image.

I've looked into the decoder dependency (dav1d), but I haven't seen a way to decode row by row either.

I already decoded an image so it will be supported in the future, but I'll hold it for some time and see if there's a better alternative.

**Comment by ccvelandres** [comment]
You could try libheif, using also dav1d as the decoder. I think it supports decoding by tiles.

**Comment by Markus40** [comment]
> That said, the decoder API of libavif is sadly very basic. You can't decode to RGB565, decode a smaller region or lower (subsample) the resolution of the image. And the worst part is that there's no way to decode the image row by row. That will make the decoder quite inefficient, as I'll need two buffers containing the full image.

AVIF is derived from the AV1 Video format. It is a very efficient format, but has a few inherent disadvantages. Images can only be loaded completely and loading lower resolutions, smaller regions, single rows or with a lower colour depth is not faster than loading the complete image. It is uncertain whether these feautures will ever be implemented, as there are already a lot of libraries that can do this.

**Comment by inorichi** [comment]
@Markus40 the problem isn't decoding speed. What I'm concerned about is memory. A big subset of images could lead to OOM issues.

Anyways, I'll work on supporting this format. Hopefully available within the next few days.

**Comment by inorichi** [comment]
The image decoder now supports HEIF and AVIF images if the [proper build option is enabled](https://github.com/tachiyomiorg/image-decoder/commit/f403b7cd6c140d81de13a8a39248b44774b044f1).

Worth mentioning that enabling those two decoders add 2.3 MB to the final APK (~700 KB per architecture and we're building for 3 archs).

If @arkon is ok with that, updating the dependency to that commit should be enough.

**Comment by wabberz** [comment]
Sorry to bump this closed issue, but testing this with the latest Preview 380, none of my test files are detected when opening a local source from a directory. It opens the image viewer when I rename some files to .png, but the circle spins forever.

My guess is that there are two parts in the code that need to be changed to support AVIF and HEIF files:

[This part](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt#L31)  uses `guessContentTypeFromName()` the derive the file type from the file name. It probably doesn't support AVIF and HEIF yet, so it fails.

[This function](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt#L42) tries to derive the actual file type from the file header, but (obviously) fails, since neither AVIF nor HEIF are listed.

**Comment by wabberz** [comment]
Anything I can do to help this along or is there a blocker?

**Comment by inorichi** [comment]
Not really. This was fixed some weeks ago in the image decoder, but I forgot to update the dependency in tachiyomi.

**Comment by wabberz** [comment]
Just compiled it myself to test and it works great, but it doesn't show a cover like it does for folders/archives with other formats.

**Comment by arkon** [comment]
Can you make a separate issue with more info?

**Comment by wabberz** [comment]
I mean, I can, but it's really easily to reproduce with the archives I posted earlier. Neither as CBZ nor as extracted folder do they show a cover, but viewing works just fine. It's not really a big issue tbh.

**Comment by arkon** [comment]
A separate issue would be better for tracking. I don't think the local source handles anything other than JPEG covers anyway.

**Comment by wabberz** [comment]
I see, I'll make a separate issue with that information then, thanks!
