### ISSUE TITLE
[Feature Request] <Lower the settings menu in reading mode>

### ISSUE THREAD

**Issue by Dddsasul** [tachiyomiorg/tachiyomi#4856]
## Why/User Benefit/User Problem
Lower the settings menu in reading mode for easier one hand usage, it is needlessly high and hard to use; it has a lot of empty space.

## What/Requirements
Nothing really to explain, I attached 2 pictures:
[https://imgur.com/a/7Xt3uvt](https://imgur.com/a/7Xt3uvt)

**Comment by paulo27ms** [comment]
You can push it down and it'll do what you want.
Currently there's an issue in preview (not sure if in stable) where it sends the last option below the buttons and you can't click it though.

**Comment by Jaykoerner** [comment]
This is a device specific fix your asking for, for example I have a tablet and that same menu has has a bank space equal to the size of your whole phone on my device, your asking for a redesign, honestly a better option in my opinion if this is deemed a issue is to have the sub menus on the bottom and the rest of the settings bottom aligned so everything is easy to reach, but that would also mean people would do the less intuitive thing scrolling up through a menu instead of down.

**Comment by arkon** [comment]
All sheets in the app should be consistent in peek height now, barring their maximum height being too short.
