### ISSUE TITLE
[Bug] <forces app to crash/close>

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi#4866]
## Device information
* Tachiyomi version: 0.10.10
* Android version: 10
* Device: samsung a10s

## Steps to reproduce
1. First step
2. Second step

Expected behavior - chapter should load fine

## Other details - already tried to clear data the app itself, uninstalled and restored my backup but to no avail when i tried again it still crashed

here is the crash log

--------- beginning of main
04-16 04:39:20.412 12649 12649 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
04-16 04:40:53.714 12649 12649 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false

**Comment by kasakaka** [comment]
note: the app crashes when reading chapters with longspread pages that have 7 pages or less but it works fine when reading manga

**Comment by arkon** [comment]
Can you upload the full crash log?

**Comment by kasakaka** [comment]
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6321143/tachiyomi_crash_logs.txt)
here

**Comment by arkon** [comment]
Unfortunately no info in that either. Judging from [your comment](https://github.com/tachiyomiorg/tachiyomi/issues/4866#issuecomment-820719892) about longspread pages, I suspect it's just running out of memory to load larger images. This is a known issue and might be addressed by #4791, so I'll close this since it's not actionable otherwise.
