### ISSUE TITLE
[Feature Request] Marked manga

### ISSUE THREAD

**Issue by HapyEnding** [tachiyomiorg/tachiyomi#4920]
## Why/User Benefit/User Problem
It can filter which manga what user want to read and what user wont to read.

## What/Requirements
This feature have same system like downloaded feature but it can filter undownloaded manga. So basically it can filter which manga that you marked.

**Comment by arkon** [comment]
This sounds like what categories are for.

**Comment by HapyEnding** [comment]
> This sounds like what categories are for.

well, i separate my library categories to their type. (e.g. Manga shounen 4 categories (separate by divide alpabhet to 4) ,manhwa shounen 3, manhua shounen 2)
I usually download the manga if i want to read it
but since the new storage feature on android 11 its hard to delete it
so it's gonna helpful if i can filter the manga that i want to read it or not (since i got bored easly and stop in midway)
Actually i can give categories "want read it right now" but since i have many manga (500+ manga) it's hard to back them in their categories

**Comment by arkon** [comment]
At best, a system for #4398 similar to TachiyomiSY/J2K would allow you to edit the tags that you can search for.

Otherwise, you can have manga in multiple categories. Selecting multiple manga to put into a category is no less effort than selecting multiple manga and somehow marking them as _something_.
