### ISSUE TITLE
[Feature Request] download button queue blink

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5007]
## Why/User Benefit/User Problem
to make it more noticeable like before instead of only the small arrow blinking

## What/Requirements
make the circle in download button blinking like the arrow while in queue
or something similar

**Comment by ivaniskandar** [comment]
Hi, I'm the one who made this change.

The reason why I didn't make the circle alpha animate is I wasn't sure if making the entire download button (since the ChapterDownloadView is technically a button) hidden is a good design. I didn't think much about the design when I made the PR since I was trying to not change the UI too much.

I'll try to tweak it further but there's only so much we can get from a developer design 🤞

**Comment by arkon** [comment]
Closed by #5213
