### ISSUE TITLE
[Feature Request] add filter or auto category error/change url

### ISSUE THREAD

**Issue by shindury26** [tachiyomiorg/tachiyomi#5016]
**Why/User Benefit/User Problem**
to make it more noticeable more user friendly and easy to use 

**What/Requirement**
add filter that only show change url can be use after update your library
to allowed easy migrate 
or
auto add to change url category after update your library and auto migrate all change all on selected extension or same extension

**Comment by wlsnbilyb** [comment]
This is really hard to read, but I believe is the same as a feature I'd like to request. When a manga has it's source changed, it's impossible to find out when updating normally, and I occasionally have to go through my list to find manga that haven't updated for a while because I need to fix the source manually.

Some method of automatically categorizing these broken/sourceless manga, like putting them in a "broken" category so that the user knows to fix them, or even the option to automatically migrate the source when available would be very helpful.

**Comment by arkon** [comment]
#4616
