### ISSUE TITLE
[Bug] Download fails if Chapters have same name

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi#5051]
## Device information
* Tachiyomi version: r3354
* Android version: 10
* Device: S10+

## Steps to reproduce
1. Download manga with 2 chapters exactly the same name/date/scanlator 

### Expected behavior
Download all Chapters

### Actual behavior
Fails to download the chapters with the same data

## Other details
Only thing different is Chapter Number and the pages being loaded 
The Chapters also don't have a upload date

**Comment by FallenWarrior2k** [comment]
I think this might be related: if you have two entries with exactly the same name from the same source that also have a chapter with the same metadata but different contents, if you download it for one of them, it'll show up as downloaded for the other as well and you can no longer access the chapter with the different contents because there doesn't seem to be a way to view a chapter directly from the source without deleting the local one.

**Comment by arkon** [comment]
Yeah, the app relies on a naming convention to associate chapter entries with downloads. If you're noticing this for a particular source, try seeing if it can be addressed at the source-level instead.
