### ISSUE TITLE
[Bug] Jumpy navbar in the new tablet interface

### ISSUE THREAD

**Issue by giosann** [tachiyomiorg/tachiyomi#5113]
App version: 0.10.12-3368 (standard, 09c07faa, 60)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.T865XXU4CUC1
Device brand: samsung
Device manufacturer: samsung
Device name: gts6l
Device model: SM-T865
Device product name: gts6leea

## Description
[video](https://youtu.be/qqanWGpHAzk)
At the moment the left navbar of the tablet interface jumps a bit up and down when switching to and from "Library" and "Browse".

It should either always stay a bit lower (like in the library and browse section) or extend to the top, moving the categories / [source/extensions/migrate] bar to the right.

**Comment by joseph619** [comment]
This is technically a bug, as the navbar isn't supposed to move at all.

**Comment by edmer664** [comment]
isn't this supposed to be labelled as a bug

**Comment by arkon** [comment]
Yeah, this is because of the tab layout in Library and Browse making the content lower than the other views.

There's 2 options here (barring any technical limitations):

1. Make the nav rail extend the full height and have all the content, including the toolbar and tab layout, to its right.
2. Keep the toolbar above the nav rail (which I believe is consistent with apps like Google Photos), and extract the tabs out.
