### ISSUE TITLE
[Feature Request] Blacklist or preferred not to show on results

### ISSUE THREAD

**Issue by KuroUsagi1010** [tachiyomiorg/tachiyomi#5128]
Would it be possible to have a user blacklist of titles? just a list of titles or series I tagged as "don't show" on results.

Chinese and Korean manga are not really my cup of tea, and most of the extensions now whether on my latest or just viewing has lots of them.

it's hard not to see them since they update much more frequently than JP Manga. and I would have to scroll down a lot to not see them. 

Disclaimer. I'm not against them, It's really not just my preference so yeah if possible a feature where we can  have preferences of which not to show.

PS. when filtering thru extensions, there are tags which are for chinese and korean titles that even if you remove will still show those titles

I don't know if this feature would make sense but I would really love it if it was implemented

## Why/User Benefit/User Problem
1. We read the title before and we may not like it (NTR, Gore) other things which goes against users preferences. and users may not want to see it again.
2. We potentially hide them from the results of "latest" or by search

## What/Requirements
1. I'm not really sure how this would be coded. I'm only thinking of getting the blacklist from user settings. check latest results if it has those titles then remove them from the results. I don't know how taxing it is to the resources of the app nor how big the feature is actually.

**Comment by GameplayerOk** [comment]
Tenho esse problema com mangás e etc... Com conteúdo +18, seria legal o desenvolvimento de um filtro personalizável com restrições de tags. Mangás ou etc... Com marcadores selecionados como manwa ou adulto seriam ocultados

**Comment by alessandrojean** [comment]
This would be ideally better implemented on an extension-basis on sources that support this type of filter, rather than in the app itself. Implementing this on the app would not be hard, but it would be a messy solution.

> Tenho esse problema com mangás e etc... Com conteúdo +18, seria legal o desenvolvimento de um filtro personalizável com restrições de tags. Mangás ou etc... Com marcadores selecionados como manwa ou adulto seriam ocultados

@GameplayerOk Isso das tags é muito dependente de cada site, se ele permite essa filtragem ou não. Extensões de sites que suportam estas categorias de restrições normalmente já tem os filtros em que você pode selecionar ou não. Além disso, se fosse implementado no app, dependeria de muitas requisições para descobrir as tags de cada mangá da listagem, e isso potencialmente só faria com que mais sites começassem a ficar lentos e a bloquearem o Tachiyomi.
