### ISSUE TITLE
[Feature Request] option to choose mobile or tablet format plus

### ISSUE THREAD

**Issue by vongdong** [tachiyomiorg/tachiyomi#5175]
The tablet manga view isn't doing it me so can we have the option of mobile or tablet view?

If not then can you please do the following:
* increase manga cover to make up at least 40% of the left column as it's too small and there's a lot of dead space at the bottom
* make the left column a bit wider to accommodate the words for 'tracking and 'webview'
* fix the search function on manga pages. Right now it doesn't do anything if I touch the title
Just including a screenshot
![Screenshot_20210525-035117_TachiyomiSY](https://user-images.githubusercontent.com/60080780/119388186-484a8580-bd0d-11eb-8feb-46be6e7caa32.jpg)

**Comment by arkon** [comment]
> increase manga cover to make up at least 40% of the left column as it's too small and there's a lot of dead space at the bottom

I may tweak this in the future if somebody comes up with a solid idea for it. It's also a bit dependant on the entry (some have much more content below).

> make the left column a bit wider to accommodate the words for 'tracking and 'webview'

Implemented in eaf9c9b2d8ef6aec525871f6652b2361fbb70442 (50% width, max of 450dp). Your particular screenshot is worse since SY shows 4 buttons, while the main app only does 3 to help avoid that (it's the same issue on smaller phone screens).

> fix the search function on manga pages. Right now it doesn't do anything if I touch the title

Addressed in 47f865aa720c47faa7853f4be3065e3ba718f1ba, title now behaves as it does on phones.

**Comment by vongdong** [comment]
Search function doesn't work. Like if I touch on undead unluck on the above screenshot it doesn't open a search in other sources like it normally should.

**Comment by arkon** [comment]
Well yes, there isn't a new build out with the referenced commits yet...

**Comment by vongdong** [comment]
> 
> 
> Well yes, there isn't a new build out with the referenced commits yet...

okay, just thought you meant it worked as you said it's been addressed.
