### ISSUE TITLE
[Feature Request] option for tablet navigation buttons in different locations

### ISSUE THREAD

**Issue by vongdong** [tachiyomiorg/tachiyomi#5177]
Can there please be an option to have the navigation buttons on tablets moved  to where ever users find them comfortable?  Top is too high and bottom is a bit too low. I use a large tablet so between the middle and bottom is most comfortable for me.

**Comment by arkon** [comment]
Since the side navigation still a relatively new component, I'm not really sure what's going to catch on and become the norm.

I may just remove the bottom alignment option in the future depending on what ends up being implemented in other apps and becomes the norm.

**Comment by vongdong** [comment]
> 
> 
> Since the side navigation still a relatively new component, I'm not really sure what's going to catch on and become the norm.
> 
> I may just remove the bottom alignment option in the future depending on what ends up being implemented in other apps and becomes the norm.

Possible to give us an option to have the buttons where ever we want? Like customizing a toolbar on a browser?

**Comment by arkon** [comment]
That's been turned down multiple times in the past.

**Comment by ronfar-x** [comment]
Could an option be added to use the old UI instead of this new side navigation thing? 
I really liked the old UI better, and it's frustrating that there is no way to use it anymore. 

The forced left side navigation buttons are also difficult to use for anyone that onehands it on the right. the bottom buttons were perfect, non-obtrusive. I don't understand the reason for forcing a new UI and removing the old one. 

In addition, I have a smaller 7 inch tablet, and the new UI smooshes everything into small columns now, so overall it's a lot more difficult to find chapters as well. Maybe this UI is better for someone rocking a 10 or 12 inch phat tablet, but it really sucks in a small tablet.

**Comment by loocool2** [comment]
Like the move in UIs from 0.8 to 0.9, there are no plans to support two different UIs
