### ISSUE TITLE
[Feature Request] Add scroll bar to browse through sources faster

### ISSUE THREAD

**Issue by Saad3894** [tachiyomiorg/tachiyomi#5205]
Please add a scroll bar to the right of the screen when browsing through manga on different sources.

Just like the one in the library, updates, history.

Also the scroll bar should display 1-100, 100-200, 300-400 etc when scrolling down.

This will very helpful in locating where you left off if the app closes or resets which forces you to start browsing from the beginning. So you don't have to keep scrolling down again.

**Comment by datreesezcup** [comment]
While this is a good idea, I don't think it would be possible to implement in the way you describe unfortunately.

Library, Updates, and History have a scrollbar because they are all based on data stored in Tachiyomi's database on the device. As such, Tachiyomi can know near instantly exactly how many items there are, and it can figure out how to setup the scroll bar.

However when it comes to sources, Tachiyomi has no way of knowing how many manga are available for a source. (and it'd be infeasible for Tachiyomi extensions to try and figure that out, if it even could in the first place). All that Tachiyomi knows when browsing sources is if there is more manga to browse (if there is another "page" of manga on the source).

However I do agree that it'd be nice if we could specifically jump to a certain page of results while browsing manga. But it brings up a couple of potential caveats about how different sources deal with pages of manga.

### Disclaimer:
I am by no means an expert on how Tachiyomi works; I am a relatively new contributor to the project, and base my answer on what I've found interacting with the code. I'd love anyone with more experience with Tachiyomi to correct me if I'm wrong about anything.

**Comment by Saad3894** [comment]
Yeah, I do hope there is a solution to this problem cause that is the only drawback I have with this app.

**Comment by arkon** [comment]
Yeah, this isn't really possible since you can't scroll through a list of data you don't have. #407 may be more sensible, but it's also problematic in how to handle scrolling when there's gaps in the data.
