### ISSUE TITLE
[Bug] Missing downloaded manga chapter

### ISSUE THREAD

**Issue by mbfedder** [tachiyomiorg/tachiyomi#5212]
Some of the manga chapters that i already downloaded doesn't show up on the library.

**Comment by AlbedoSuzuki** [comment]
Maybe the chapter was auto-renamed or something like that
You can check this relatively simply by noting down the chapter-Name
then Re-Download the Chapter and Check again.
When this happens to a single Chapter it it not really noteworthy that happend 
to me by over a thousand Chapters already.
Btw. What source do you use?

**Comment by CrepeTF** [comment]
What source are you using

**Comment by 10lalib** [comment]
Hello
I have the same problem. I am using the mangakakalot source and the sourcewebsite name changed from manganelo.com to readmanganato.com
Was the change done by mistake? Because of it the downloaded chapters before are not available for reading and it will require either manual renaming or redownloading.
Please help fixing it
Thank you![Screenshot_20210529-151459_My Files.jpg](https://user-images.githubusercontent.com/61493858/120068256-445d9100-c088-11eb-8b73-424d5e3e289c.jpg)

**Comment by CrepeTF** [comment]
Just rename the folders

**Comment by CrepeTF** [comment]
This was not a mistake, the naming follows the sources website, and since they changed it, the naming changed too.

This is not a bug

**Comment by 10lalib** [comment]
Any solution for this? Or will have to rename the old chapters manually?

**Comment by 10lalib** [comment]
> Any solution for this? Or will have to rename the old chapters manually?

I just moved to local source and everything was there so will use it until i read all the chapters and the remove it
