### ISSUE TITLE
[Bug] App crashes when searching

### ISSUE THREAD

**Issue by ironmaideneddie** [tachiyomiorg/tachiyomi#5231]
## Device information
* Tachiyomi version: 0.10.12
* Android version: 9
* Device: Huawei MediaPad M5 (Model: CMR-W09)

## Steps to reproduce
1. Open Tachiyomi
2. Open any manga
3. Press the manga name to search for that manga
4. Or
5. Go to the Browse tab and search for a manga

### Expected behavior
The app searches amongst your installed sources and gives you results

### Actual behavior
The app crashes after the search has been running for about 30-40 seconds

## Other details
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/6564312/tachiyomi_crash_logs.txt)

**Comment by AwesomeQuest** [comment]
I have the same problem. I think it's a specific extension because it doesn't happen with all searches and only happens at a certain point in the search. Can't see which extension though.

The searches that crash are:
Skeleton Soldier Couldn’T Protect The Dungeon
Slave Of The Magic Capital's Elite Troops

But not:
Skeleton Soldier (Skeleton Soldier Couldn’T Protect The Dungeon)

Here are the relevant crash logs.
[Skeleton Soldier Couldn’T Protect The Dungeon.txt](https://github.com/tachiyomiorg/tachiyomi/files/6564378/Skeleton.Soldier.Couldn.T.Protect.The.Dungeon.txt)
[Slave Of The Magic Capital's Elite Troops.txt](https://github.com/tachiyomiorg/tachiyomi/files/6564380/Slave.Of.The.Magic.Capital.s.Elite.Troops.txt)

**Comment by AwesomeQuest** [comment]
Update: the bug has no stopped.

**Comment by CrepeTF** [comment]
Someone close this issue
