### ISSUE TITLE
[Bug] truncated chaper list in manga view

### ISSUE THREAD

**Issue by nille02** [tachiyomiorg/tachiyomi#5272]
## Device information
* Tachiyomi version: 0.11.1
* Android version: 11
* Device: Galaxy Tab S6

In the new Version the Chapter Names are truncated. The Manga Information now fill half the screen. Is there a way to change the config that the information are now back on the top and that they fade out if i scroll down? then the space would be free again for the chaper names. 

![Screenshot_20210602-091154_Tachiyomi](https://user-images.githubusercontent.com/4272018/120439486-dc0df880-c382-11eb-962a-9c76eedb11ad.jpg)

**Comment by nille02** [comment]
Other ways could be a line break in the name or a horizontal scrolling name

**Comment by ronfar-x** [comment]
Alternatively, could an option be added to allow the old UI where the list of chapters was from mid to bottom of the screen again? This new UI is needlessly wasteful of the screen, and overall a bother to use.

**Comment by bgarnz** [comment]
Popping in to say that this is not just a UI preference - resources I use put the issue number at the end of the filename, so all of my files are now unreadable.

**Comment by kiriya-aoi** [comment]
Line breaks would be a better option than reverting. There have always been titles that run off-screen, on all devices. We have gotten a fair number of complaints about it from phone users as well. Multiline could mitigate or solve this for a wide variety of devices, rather than simply ignoring the problem.

Scrolling is not a solution, it relies on things moving. Ignoring the accessibility concern, you cannot at a glance read the whole title, or even just the part of the title you might be looking for like a number.

**Comment by arkon** [comment]
Advanced setting allows for only using the tablet layout in landscape, which would typically have a more reasonable amount of space to show content in the right column.

**Comment by nille02** [comment]
Thank you for your work. I installed the 12.x Version now after arkons comment. and the old view is back on tablets. 

Just my local files with a longer name i got the problem of truncation but that can easily fixed on my side.
