### ISSUE TITLE
Touching the SearchView title(last query) should enable to enter a search request

### ISSUE THREAD

**Issue by gan-of-culture** [tachiyomiorg/tachiyomi#5691]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

**This is only really important if you already searched for something and then you want to search for something else.**

Instead of having to always tap the search icon in the explore menu if you want to search something, I would suggest that tapping the search bar itself also enables to input a new search query.

Why?
Because in my opinion is more intuitive to search this way. For me the search icon next to the bar is more like a send button so if you put in something and you wanna start the search you press on the icon. Also the icon might be more difficult to reach, because it's in the most top right cornor.

It would be really nice to have.

**Comment by vengiare** [comment]
I'm guessing you're talking about global search.

A different suggestion I have that solves the same problem would be

Instead of this:
![IMG_20210811_070112](https://user-images.githubusercontent.com/63973749/128945727-83e4ea4b-38e0-429e-b1f9-2e56abcfd794.jpg)

where you have to click the search icon to edit the text, Global search bar should act the same way like Source search instead:
![IMG_20210811_070135](https://user-images.githubusercontent.com/63973749/128945875-ee08a6e2-6447-4200-9a79-9834c6494fb1.jpg)

Where you could easily edit the text, and also click the clear button if you want a new search query.

**Comment by gan-of-culture** [comment]
Exactly yes

**Comment by gan-of-culture** [comment]
If found this https://stackoverflow.com/questions/30455723/android-make-whole-search-bar-clickable and I will give it a try

**Comment by gan-of-culture** [comment]
Looks like something like this already was implemented?
#3265

It's not working tho? If I click the Title of the Globalsearch in Sources it doesn't open the search?

**Comment by gan-of-culture** [comment]
@arkon perhaps this is a bug instead?

**Comment by arkon** [comment]
Closing in favour of #7201
