### ISSUE TITLE
High CPU usage and battery drain

### ISSUE THREAD

**Issue by josepmdc** [tachiyomiorg/tachiyomi#5702]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

Onyx Boox Nova 3

### Steps to reproduce

1. Open the app
2. Open any Manga and start reading
3. After a few seconds the device starts heating up

### Expected behavior

The device doesn't heat up, and battery isn't drained.

### Actual behavior

T'he device heats up and battery is drained faster than usual.

### Other details

I've been using v12 for a few days and I noticed the device starts heating up after a little while. I tested with v11 and TachiyomiJ2K and it didn't heat up with neither. Is there something in the new update that could be causing this overheating and consequently a battery drain?

**Comment by AlgusDark** [comment]
This happened to me. I downgraded to v11. For me, the reader was super slow too.

**Comment by Bersy1** [comment]
Just finished testing on my Onyx Boox Poke 3 and it's draining 8% per hour without back-light and OVER 20% per hour with back-light on, mind you J2K uses around 3% per hour with back-light off and just about double that with the back-light, this might be related to Onyx eReaders but i doubt it doesn't affect other devices.

**Comment by keyjeyelpi** [comment]
I experience the same thing with my galaxy note 8. I think it's due to the updating of the libraries since the lag only occurs upon update. The fact that it still tries to update despite finishing all the scans cause the device to heat up a lot. Here's how much the battery drained. *note that I was fast charging my phone, so for it to decrease and turn off due to Tachiyomi is a big issue.
![Screenshot_20210819-063114_Device care](https://user-images.githubusercontent.com/49813589/129981427-aad05299-b749-4ae5-a944-e723613b22d0.png)

**Comment by Bersy1** [comment]
> 
> 
> I experience the same thing with my galaxy note 8. I think it's due to the updating of the libraries since the lag only occurs upon update. The fact that it still tries to update despite finishing all the scans cause the device to heat up a lot. Here's how much the battery drained. *note that I was fast charging my phone, so for it to decrease and turn off due to Tachiyomi is a big issue.

Jesus Christ talk about battery hog, I'm surprised more people aren't complaining, i thought it was related to Onyx devices but it seems like it's a global thing, consuming so much battery in such little time could also decrease the life expectancy of the battery, i recommend you go to another fork in the meantime, i went back to J2K since first posting and tested again, it uses 2% in an hour no matter if have the back-light on or off. Def a Tachiyomi issue.
My guess is that not enough people regularly update, because there's no way you don't notice 1/5 of your battery gone after reading for just an hour.

**Comment by onmyouji** [comment]
Tachiyomi version: 0.12.1
Android version: 11
Device: Nokia 5.3
 
I also experience similar issue, Tachiyomi drains so much battery. 

When I checked the battery usage on Android, it showed that Tachiyomi was always in active use (not running in background), even when I had already closed the app and turned off my phone screen. On Tachiyomi Global update settings, my update frequency is also set to manual.

Seems like I have to force stop the app, because exiting normally clearly doesn't work. The app never runs in background.

**Comment by ivaniskandar** [comment]
It'd be a tremendous help if anyone with this issue can try the preview builds from the past weeks and find which one spawns the issue. I recommend starting from [here](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r3571) and then move to newer builds.

**Comment by TacoTheDank** [comment]
@ivaniskandar Would something like a logcat reader be able to catch anything pertaining to this?

**Comment by onmyouji** [comment]
> It'd be a tremendous help if anyone with this issue can try the preview builds from the past weeks and find which one spawns the issue. I recommend starting from [here](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r3571) and then move to newer builds.

I've been using r3571 on my phone for almost a week. Seems like this build works quite well on my phone. I'm new to tachiyomi, so I don't know whether this battery usage is considered good or not, when compared to the release before 0.12.1

Here's a screenshot of the battery usage:

Tachiyomi version: r3571
Android version: 11
Device: Nokia 5.3

![tachiyomi screenshot](https://user-images.githubusercontent.com/8424198/130760511-88c9b584-611a-46bc-aa13-cf39d27c35a5.png)

**Comment by arkon** [comment]
Are newer versions any better?

**Comment by keyjeyelpi** [comment]
> Are newer versions any better?

Nope. Still has the same battery drain on mine. It won't stop checking for updates, even when finished

**Comment by TacoTheDank** [comment]
This is something I'd really like to get to the bottom of. Active engagement is the only feasible way I see this issue being tackled sooner rather than later.

There are [186 commits](https://github.com/tachiyomiorg/tachiyomi/compare/v0.11.1...v0.12.0) between v0.11.1 and v0.12.0. @josepmdc stated that this started with the v0.12.0 build, so I think it would be ok to assume that the culprit must be at least one of these commits.

Since most of the builds from back then have disappeared by now, I'm going to go and generate debug APKs for every **20** commits (because 186 is a lot, obviously). I would like you guys (or any willing testers) to test how each one runs over a period of time. Please test each one in succession (or start wherever, it doesn't really matter tbh) and let me know if the APK has the battery issues. From there, we can continue narrowing it down with more test builds.

If you can, export the database from your main Tachiyomi app and import it into these, and use them for a while. Once you're able to find the build where the battery issues start occurring, please tell me which build.

I will be signing the APKs with my own key, but I don't think that should be a problem.

...at least, that's the plan I'm putting forth. Does anyone have any disagreement with this? (Or maybe a recommendation for the amount of commits to generate APKs for?) I'd like to have at least some confirmation before I go ahead with it.

**Comment by vengiare** [comment]
> josepmdc stated that this started with the v0.12.0 build

Wait was ot 0.12.1 or 0.12.0

#

6 or less APKs should be enough at first, then split the commits again when we get an idea of which build introduces the usage spike. 9 builds would be a pain to test each.

**Comment by arkon** [comment]
r3571 corresponds to commit d9ea621e544981062c2a67b8f4bb196cb0da904f, so you can start from there.

v0.12.0 (f48b2681e31933f12e03d709e27abffaf260a760) corresponds to r3657, so there's only 86 commits in between. You could always do a more binary search-y approach (i.e. keep halving it) if you don't want to have a ton of APKs to test.

0.12.0 and 0.12.1 don't really have any notable difference, so easier to just go with 0.12.0.

**Comment by onmyouji** [comment]
I hope users like OP who had their device heating up would be willing to help. Because physical property like temperature is easier to verify than battery usage. 

I don't experience any overheat on my device so when doing the battery test, I had to wait 1-2 hours to get any result. And android's battery reading can be inaccurate sometimes.

**Comment by keyjeyelpi** [comment]
> This is something I'd really like to get to the bottom of. Active engagement is the only feasible way I see this issue being tackled sooner rather than later.
> 
> There are [186 commits](https://github.com/tachiyomiorg/tachiyomi/compare/v0.11.1...v0.12.0) between v0.11.1 and v0.12.0. @josepmdc stated that this started with the v0.12.0 build, so I think it would be ok to assume that the culprit must be at least one of these commits.
> 
> Since most of the Dev builds from back then have disappeared by now, I'm going to go and generate debug APKs for every **20** commits (because 186 is a lot, obviously). I would like you guys (or any willing testers) to test how each one runs over a period of time. Please test each one in succession (or start wherever, it doesn't really matter tbh) and let me know if the APK has the battery issues. From there, we can continue narrowing it down with more test builds.
> 
> If you can, export the database from your main Tachiyomi app and import it into these, and use them for a while. Once you're able to find the build where the battery issues start occurring, please tell me which build.
> 
> I will be signing the APKs with my own key, but I don't think that should be a problem.
> 
> ...at least, that's the plan I'm putting forth. Does anyone have any disagreement with this? (Or maybe a recommendation for the amount of commits to generate APKs for? Is 20 too small to start with?) I'd like to have at least some confirmation before I go ahead with it.

I'd be happy to test it after 2 days. Can we maybe chat in telegram for the convenience?

**Comment by loocool2** [comment]
@keyjeyelpi We don't use Telegram, go to the Discord instead

**Comment by TacoTheDank** [comment]
> r3571 corresponds to commit [d9ea621](https://github.com/tachiyomiorg/tachiyomi/commit/d9ea621e544981062c2a67b8f4bb196cb0da904f), so you can start from there.
> (i.e. keep halving it)

Yeah I was actually thinking to do it that way instead. I didn't update the comment though to mention that.

@loocool2 hmm, I'm already in the Discord server (although not active in it). What channel would be best for discussion? `#programming`?

**Comment by josepmdc** [comment]
> ~~Wait was ot 0.12.1 or 0.12.0~~
> 
> #
> 
> 6 or less APKs should be enough at first, then split the commits again when we get an idea of which build introduces the battery drain spike. 9 builds would be a pain to test each.

This sounds good to me. I'm open to testing the APKs on my device if you need.

**Comment by TacoTheDank** [comment]
Okay, so here's the first build. I chose commit 3571, as @arkon suggested. Also, it's pretty much in the middle, so it's good to start with. Please test and report the results.

[v3571.zip](https://github.com/tachiyomiorg/tachiyomi/files/7220815/v3571.zip)

**Comment by loocool2** [comment]
@TacoTheDank ``#programming`` would work

**Comment by josepmdc** [comment]
> Okay, so here's the first build. I chose commit 3571, as @arkon suggested. Also, it's pretty much in the middle, so it's good to start with. Please test and report the results.
> 
> [v3571.zip](https://github.com/tachiyomiorg/tachiyomi/files/7220815/v3571.zip)

I tested this build and I didn't notice any overheating, so I'd say this commit is good.

**Comment by keyjeyelpi** [comment]
So, I tested ever single build from 3571 up to 3812. Weirdly enough, I've never experienced any heating issue nor any spikes in the battery

**Comment by z3r0r4** [comment]
> Update 2: the automatically refresh metadata is apparently the one causing the infinite update and battery issue.

thank you very much!
this seems to fix the issue!

**Comment by z3r0r4** [comment]
The overheating also seems to be verifiable device dependent. As it occurs on my S10 but not on the phone of a friend. v12.3
