### ISSUE TITLE
Anilist Show Title according to account setting. 

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#5757]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

My account is set to show titles in English but in track search it shows in romaji(?)

**Comment by curche** [comment]
This is because the [Search](https://github.com/tachiyomiorg/tachiyomi/blob/4eaccc966eba26a47ed3e6d645dcccf8a4edf8ea/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt#L108) query used by Tachi is, afaik, user agnostic i.e. it is independent of the user for now

However, considering how the user has to be logged in to actually search and how their site (and other unofficial AL-Clients as well?) is able to do that using `userPreferred`, let me try if it works. 

btw, for the curious, this is the [query](https://anilist.co/graphiql?query=query%20(%24page%3A%20Int%20%3D%201%2C%20%24id%3A%20Int%2C%20%24type%3A%20MediaType%2C%20%24isAdult%3A%20Boolean%20%3D%20false%2C%20%24search%3A%20String%2C%20%24format%3A%20%5BMediaFormat%5D%2C%20%24status%3A%20MediaStatus%2C%20%24countryOfOrigin%3A%20CountryCode%2C%20%24source%3A%20MediaSource%2C%20%24season%3A%20MediaSeason%2C%20%24seasonYear%3A%20Int%2C%20%24year%3A%20String%2C%20%24onList%3A%20Boolean%2C%20%24yearLesser%3A%20FuzzyDateInt%2C%20%24yearGreater%3A%20FuzzyDateInt%2C%20%24episodeLesser%3A%20Int%2C%20%24episodeGreater%3A%20Int%2C%20%24durationLesser%3A%20Int%2C%20%24durationGreater%3A%20Int%2C%20%24chapterLesser%3A%20Int%2C%20%24chapterGreater%3A%20Int%2C%20%24volumeLesser%3A%20Int%2C%20%24volumeGreater%3A%20Int%2C%20%24licensedBy%3A%20%5BString%5D%2C%20%24genres%3A%20%5BString%5D%2C%20%24excludedGenres%3A%20%5BString%5D%2C%20%24tags%3A%20%5BString%5D%2C%20%24excludedTags%3A%20%5BString%5D%2C%20%24minimumTagRank%3A%20Int%2C%20%24sort%3A%20%5BMediaSort%5D%20%3D%20%5BPOPULARITY_DESC%2C%20SCORE_DESC%5D)%20%7B%0A%20%20Page(page%3A%20%24page%2C%20perPage%3A%2020)%20%7B%0A%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20total%0A%20%20%20%20%20%20perPage%0A%20%20%20%20%20%20currentPage%0A%20%20%20%20%20%20lastPage%0A%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%7D%0A%20%20%20%20media(id%3A%20%24id%2C%20type%3A%20%24type%2C%20season%3A%20%24season%2C%20format_in%3A%20%24format%2C%20status%3A%20%24status%2C%20countryOfOrigin%3A%20%24countryOfOrigin%2C%20source%3A%20%24source%2C%20search%3A%20%24search%2C%20onList%3A%20%24onList%2C%20seasonYear%3A%20%24seasonYear%2C%20startDate_like%3A%20%24year%2C%20startDate_lesser%3A%20%24yearLesser%2C%20startDate_greater%3A%20%24yearGreater%2C%20episodes_lesser%3A%20%24episodeLesser%2C%20episodes_greater%3A%20%24episodeGreater%2C%20duration_lesser%3A%20%24durationLesser%2C%20duration_greater%3A%20%24durationGreater%2C%20chapters_lesser%3A%20%24chapterLesser%2C%20chapters_greater%3A%20%24chapterGreater%2C%20volumes_lesser%3A%20%24volumeLesser%2C%20volumes_greater%3A%20%24volumeGreater%2C%20licensedBy_in%3A%20%24licensedBy%2C%20genre_in%3A%20%24genres%2C%20genre_not_in%3A%20%24excludedGenres%2C%20tag_in%3A%20%24tags%2C%20tag_not_in%3A%20%24excludedTags%2C%20minimumTagRank%3A%20%24minimumTagRank%2C%20sort%3A%20%24sort%2C%20isAdult%3A%20%24isAdult)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20title%20%7B%0A%20%20%20%20%20%20%20%20userPreferred%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20coverImage%20%7B%0A%20%20%20%20%20%20%20%20extraLarge%0A%20%20%20%20%20%20%20%20large%0A%20%20%20%20%20%20%20%20color%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20startDate%20%7B%0A%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20month%0A%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20endDate%20%7B%0A%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20month%0A%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20bannerImage%0A%20%20%20%20%20%20season%0A%20%20%20%20%20%20description%0A%20%20%20%20%20%20type%0A%20%20%20%20%20%20format%0A%20%20%20%20%20%20status(version%3A%202)%0A%20%20%20%20%20%20episodes%0A%20%20%20%20%20%20duration%0A%20%20%20%20%20%20chapters%0A%20%20%20%20%20%20volumes%0A%20%20%20%20%20%20genres%0A%20%20%20%20%20%20isAdult%0A%20%20%20%20%20%20averageScore%0A%20%20%20%20%20%20popularity%0A%20%20%20%20%20%20nextAiringEpisode%20%7B%0A%20%20%20%20%20%20%20%20airingAt%0A%20%20%20%20%20%20%20%20timeUntilAiring%0A%20%20%20%20%20%20%20%20episode%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20mediaListEntry%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20status%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20studios(isMain%3A%20true)%20%7B%0A%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20isMain%0A%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22search%22%3A%20%22blue%20box%22%0A%7D) used by [Browse Manga > Search](https://anilist.co/search/manga?search=blue%20box) on AL website (Credits to everyone's beloved Network inspector)

**Comment by ghostbear** [comment]
> However, considering how the user has to be logged in to actually search and how their site (and other unofficial AL-Clients as well?) is able to do that using `userPreferred`, let me try if it works.

It will work because the HTTP client is authenticated with the user
