### ISSUE TITLE
Images downloaded as binary are not saved with correct file extension

### ISSUE THREAD

**Issue by Arraiment** [tachiyomiorg/tachiyomi#5792]
### Steps to reproduce

Using Tsumino extension, search for `id:52069` and download the chapter.

### Expected behavior

Images are saved with valid image file extensions and can be viewed on Tachi after downloading.

### Actual behavior

Images are saved as .bin files and chapter cannot be read on Tachi.

### Tachiyomi version

0.12.1

### Android version

11

### Device

Samsung S9

### Other details

Related issue #4804 and [ext](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6468#issue-853055451). I'm not sure about the whole root dir in Chinese thing, but the http response for image urls in some Tsumino galleries is `Content-Type: application/octet-stream`. I had a look in [Downloader.kt](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L438) and it doesn't seem like it can correctly figure out the image type from such file headers 100% of the time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Do you have any other website that returns this header? Currently Tsumino is down so I can't check specified example 
![Screenshot_20210825-073416695 (1)](https://user-images.githubusercontent.com/57241064/130791307-1f665640-e809-4b83-817b-a14941205056.jpg)

**Comment by Arraiment** [comment]
That's weird, it was up when I submitted the issue. To my knowledge no other source serves images like that, I checked 18comic.org as well (source from #4804) but they seem to be using normal image urls now.

**Comment by paulo27ms** [comment]
It's back up now.
52069 and other newer manga don't have an extension when you try to download them through your browser (you can see in the save menu there's no extension).
But 41667 for example is fine, it has an extension when you try to download and on Tachiyomi it also downloads with the proper extension.
My guess is that since the images don't have an extension, Tachiyomi just labels them as .bin files.
This would be to fix on Tsumino's side. 
I suppose on Tachiyomi's side instead of using .bin files they could just be labeled as jpg/png, though we don't really have a way to find out which it is, there's no different in the elements of both manga, the browser code is the same.

**Comment by Seishirou101** [comment]
I thought I remembered arkon saying he put in a check if it can't find the image type, it'll default to jpg but I'm too monke to understand if it was added in the downloader.kt. However, I found something interesting when trying to find where arkon said that. There was another [issue](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/2480) that is really similar and even had a fix in the extension. So that may be what needs to be done to the tsumino ext

**Comment by Arraiment** [comment]
> I thought I remembered arkon saying he put in a check if it can't find the image type, it'll default to jpg

The downloader only defaults to jpg when the website does not respond with a content-type. In Tsumino's case it does respond with a content-type but it seems `octet-stream` is too generic for `getExtensionFromMimeType(mime)`  to return an image format. If this is too much of an edge case to warrant changing the main app I guess adding interceptors to affected extensions will work instead.

**Comment by Arraiment** [comment]
As arkon has mentioned in tachiyomiorg/tachiyomi-extensions#2480, I'm closing this in favour of handling such issues on the extensions side, like https://github.com/tachiyomiorg/tachiyomi-extensions/commit/85bfd0da30f45a6d55e6ace1a73897bfdca162f3 and https://github.com/tachiyomiorg/tachiyomi-extensions/commit/925fb1e3a650ac22e7396de0bd560b3b310a3321
