### ISSUE TITLE
Automatic background colour

### ISSUE THREAD

**Issue by Cerxi** [tachiyomiorg/tachiyomi#584]
At the moment, the only options for background colour are black or white. This is fine (after all, white is the right answer almost all of the time), but there are some apps (CBLoader, for example) that have a very basic "automatic" background setting, and I think Tachiyomi could benefit from implementing the same, to prevent white borders on the occasional black page.

The easiest version is to sample a single pixel (usually (0,0), the top-leftmost) of each page, and set the background colour to that, since most manga pages have generous blank margins and so the (0,0) pixel will be the right colour nearly every time.

A slightly more involved version is sampling eight or so pixels from various points around the edges (mostly top and bottom) and checking if more of them are black or white. I don't think that's really necessary, but if you felt like it, it's an idea!

**Comment by inorichi** [comment]
It's feasible. Gave it a try and it doesn't require many changes to the image library (only allowing access to the bitmap).

However there are a few points I'm still not sure about.

There has to be a default background color, because until the image is decoded I can't access its pixels, so this would probably be an additional setting instead of a new background color entry.

Synchronizing the page indicator can be very tricky, probably I would have to use the selected background color and never change it (as it's working atm).

Sampling only the first pixel is not good, and I think the number of sampled pixels should be odd. With an even number of pixels we could have the same amount of pixels in black and white, and the algorithm would have to decide whether to consider that case as white or black. I'm thinking of 5 pixels, each corner and the pixel in the middle of one side.

To calculate the resulting color, I'll probably use [this](https://developer.android.com/reference/android/graphics/Color.html#luminance(int)) method (it was added in API 24, but I can copy the method). Then by doing an average of the N sampled pixels we can decide if the image is black (< 0.5) or white (>= 0.5).

**Comment by amywoodehy** [comment]
Why not use linear gradient sampling top row of pixels and bottom row?

**Comment by joseph619** [comment]
Automatic background color exists in J2k I think, maybe it could be imported to Stable 0.9.0

**Comment by ghostbear** [comment]
When it comes to automatic background color which one of these is more preferable, left or right?

React with :+1: for left and :-1: for right

**WARNING: THE VIDEO CONTAINS SOME NSFW CONTENT**

https://user-images.githubusercontent.com/6576096/116134845-a9604880-a6d0-11eb-9a47-250a9fb56c87.mp4

**Comment by joseph619** [comment]
what is the difference? i see right one is mostly white background and rarely changed

**Comment by ghostbear** [comment]
I don't really want to say the real difference, yet, because I want an unbiased opinion on which one people prefer more.

~One of them is J2K~

**Comment by arkon** [comment]
I think the different top/bottom (from the left) would look nicer if the content near the edge was actually more black when it shows up as black.

**Comment by OncePunchedMan** [comment]
i like how it changes according to the page. but i also get how this could annoy users

**Comment by Cerxi** [comment]
Do not like different top/bottom
