### ISSUE TITLE
Add a warning when the user has a huge download queue or global update list

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi#5950]
### Describe your suggested feature

Some users have a huge library and keep checking if there are new chapters for all items instead of using categories and turning on the "Only update ongoing manga" option, causing damage to the sites. Meanwhile, there also users that put a huge amount of chapters in the same time in the download queue.

This behaviour indirectly is causing some damage to the site servers and also causing a lot of them to starting blocking the extension requests or requesting the extension removal. It would be good if the app warns these users if they are downloading a lot of stuff or updating a gigantic library. Not all users would read or care about it, but it would help a little.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment]
If we're getting desperate then on the extension side there could be some code that only lets the user update manga automatically in that extension once a day or some other appropriate time restriction (only refreshing manga data, search and downloads obviously shouldn't be affected), manual updating could bypass this to be less intrusive. We don't necessarily need to make this the default behavior but it could be another way to save some extensions. 

More on the app side and if we wanted to get really extreme then after X manga the user would need to be forced to split the library into categories or only the ones that haven't been recently checked will update until X amount and it'd rotate between the manga every cycle.

I already have another issue up for more options in terms of less intrusive/irregular library updating but even if that or more warnings are added, they'll never fix the issue some sites have with the app because users won't use the options or read the warnings. They'll set to the lowest possible time and call it a day.

**Comment by alessandrojean** [comment]
> If we're getting desperate then on the extension side there could be some code that only lets the user update manga automatically in that extension once a day or some other appropriate time restriction (only refreshing manga data, search and downloads obviously shouldn't be affected), manual updating could bypass this to be less intrusive. We don't necessarily need to make this the default behavior but it could be another way to save some extensions.

That is also a valid and good suggestion, some additional properties in the source class that would control it, like the update time you suggested or disabling download, dunno. Probably something to be suggested to the 1.x rewrite.

> they'll never fix the issue some sites have with the app because users won't use the options or read the warnings

Unfortunately, but a non-intrusive warning would still help a little.
