### ISSUE TITLE
Manga Updates (Baka-Updates) Sync

### ISSUE THREAD

**Issue by Nogooduser** [tachiyomiorg/tachiyomi#624]
Would it be possible to add syncing to this website? I figured this would be a popular feature request here, but I've looked through the issues page and didn't see anyone bring it up. I apologize if someone's asked for this before and I just didn't see it.

Main reason: One of the primary features I and many others love about Tachiyomi is the ability to sync series to MAL. Unfortunately, MAL's manga catalog is rather limited due to their scrict requirements for series. [Manga Updates](https://www.mangaupdates.com/) has one of the largest manga catalogues out there and is used by many users to keep track of their manga.  It includes web comics, doujins and other categories that most other sites won't accept. Being able to sync tachiyomi with manga updates account would save me and many others a lot of trouble since currently we have to manually update our MU lists with all the series MAL doesn't have that we can read on tachiyomi.

**Comment by inorichi** [comment]
Do they provide an API? I can't find anything and parsing is a nuisance...

**Comment by wopian** [comment]
They don't provide an API. They've supposedly been working on an API for the past 3 years...so yeah.

**Comment by Nogooduser** [comment]
If I recall correctly, there were talks about making an API for the site like 3 years ago, but I don't believe much came out of it.

The site has basically only maintained itself for years now with not much development (if any) going on behind the scenes.

**Comment by lifeweaver** [comment]
Looks like MangaUpdates has a json interface, on Mar 19 the admin Manick [said](https://www.mangaupdates.com/showtopic.php?tid=43465): 

> You can add &output=json or &output=xml or &output=jsonp etc to the search and it will output in those formats ... will only give the first 50 pages though. That's been there for years.
Also doesn't do descriptions or anything at this time. Kinda started this project a while back and never got anywhere.
example: https://www.mangaupdates.com/series.html?letter=A&output=jsonp&page=5

Once you have the id you can imitate the site ajax calls i.e. to add naruto to your reading list:
`https://www.mangaupdates.com/ajax/list_update.php?s=15&l=0&cache_j=26140203,20665467,20711279`

Where `s=15` is the id of the manga, `l=0` is the list your adding to, and `cache_j=26140203,20665467,20711279` was merely created with: `Math.floor(Math.random()*100000000) + "," + Math.floor(Math.random()*100000000) + "," + Math.floor(Math.random()*100000000)`

Plus you have to login and get the cookies so the site knows who you are.

I add this info as right now I'm not interested enough to code it, but I think if someone is, it seems doable. Plus since the site has only been maintained it's unlikely to change. Although I don't know the protocol on this kind of thing, should the site admin be asked if this is ok?

**Comment by kimphuongbc** [comment]
One Piece Chapter 879 One of Big Mom's three sweet commanders katakiru English
Link view : https://www.youtube.com/watch?v=n54gF04_D7Q
Good chapter, Big Mom is still being persistent. But onto the main thing... Katakuri is so strong, I do believe Luffy will come up with something in order to defeat him, maybe Gear 5th or Gear 4th but a different form of it. I'm curious how Oda will handle this fight.

**Comment by Bm12347** [comment]
I have been searching about random things in manga updates and found this i don't know if it helps or not








Since it doesn't seem like this info is available anywhere on the internet, and the developers have not revealed that there is in fact a hidden API, I thought I might as well post it for anyone who finds my research useful.

I was looking to use MU data, and I'm sick of parsing HTML soup on this site. Thankfully the pages are simple and static enough that it's not difficult, but it's just not right. So I found out that MU has/had an iOS app at some point, screenshots/info here: https://applion.jp/iphone/app/598640522/ (I don't have iOS devices). Then based on forum complaints about app errors containing the phrase "application/json" I figured there must be a JSON API somewhere.
Hmmm https://www.mangaupdates.com/api/ returns nginx 403... that means it's a folder! Then I took an obvious endpoint, https://www.mangaupdates.com/api/series.php and sure enough, there is a hidden API! But all I got was a "Version is required." error. I tried all sorts of url parameters and headers, and finally got a hit with the super secret "API-Version" header (using 1.1.0 because it's latest version of the app on that listing page). And yes, it actually works. Example:

Quote

curl -H "API-Version: 1.1.0" "https://www.mangaupdates.com/api/series.php?id=1"

{
"seriesName":"Open Sesame",
"description":"Danjou Yamato is a high-school student who lives in the countryside and is the boxing champion of the region. However, when his family has to move out to live in Tokyo, he is transfered to a school in Tokyo that was previously an all-girls school. Girls have a lot of power and give the guys a hard time. But Yamato will not bow down to the power of the girls, and on his way to claim power for the guys in the school, he finds out something about his past... something that he had forgotten long ago...",
"year":"2001",
"licensed":"Yes",
"countryStatus":"20 Volumes (Complete)",
"serialzation":"N\/A",
"type":"Manga",
"genre":"Comedy\r\nDrama\r\nHarem\r\nRomance\ r\nSchool Life\r\nShounen",
"completlyScanlated":"Yes",
"englishLicensed":"Yes",
"imageURL":"https:\/\/www.mangaupdates.com\/i mage\/i164349.jpg",
"authors":"KAWAKATA Kaoru",
"artists":"KAWAKATA Kaoru",
"originalPublisher":"Kodansha",
"englishPublisher":"MANGA.CLUB (Ch. 69.5 - Ongoing;digital)\r\nMedia Do (5 Vols - Ongoing; digital)",
"associatedNames":"A\u00e7\u0131k Susam\r\nOpen Sesame\r\n\u30aa\u30fc\u30d7\u30f3\u30bb\u30b5\u30df\uff0 8\u6cb3\u65b9 \u304b\u304a\u308b\uff09\r\n\u604b\u7231\u65b0\u9c9c\u4eb a",
"relatedSeries":"N\/A",
"animeStatus":"N\/A",
"listID":null
}


So now what? Well maybe some MU developers or community members can help figure out the rest of the endpoints and parameters they accept. Based on the screenshots, stuff like login, reading lists, search, releases must exist. Endpoints I've found so far:

Quote

https://www.mangaupdates.com/api/series.php
https://www.mangaupdates.com/api/releases.php
https://www.mangaupdates.com/api/search.php



I hope this helps...

**Comment by AriaMoradi** [comment]
I guess the api could be useful, but still not a lot of interested people in this feature...

**Comment by CrepeTF** [comment]
I beg to differ

**Comment by jopejoe1** [comment]
> curl -H "API-Version: 1.1.0" "https://www.mangaupdates.com/api/series.php?id=1"

Doesn't seem to work anymore getting 404 from it

**Comment by mm12** [comment]
I _sorta_ want this

**Comment by tagno25** [comment]
Mangaupdates now has an official API with documentation available at https://api.mangaupdates.com
