### ISSUE TITLE
Option to not animate animated cover across the app.

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#6452]
### Describe your suggested feature

Title

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Coil/the system APIs don't really expose an option for this since it wouldn't make sense since it's effectively like saying "I want to load a video but not play it".

You could always set a custom cover or try to have an entry without an animated cover (i.e. using a different source, or changing it at the source if possible).
