### ISSUE TITLE
Resume button crashes the app

### ISSUE THREAD

**Issue by andrewSalemi** [tachiyomiorg/tachiyomi#6529]
### Steps to reproduce

1. Open any manga that have at least one page read
2. Press the resume fab button

### Expected behavior

Open the chapter at the last read page

### Actual behavior

The app completely close

### Crash logs

--------- beginning of system
--------- beginning of main
01-31 22:45:37.667  6537  6537 E HwResourcesImpl: readDefaultConfig : FileNotFoundException
01-31 22:45:37.955  6537  6606 E SQLiteLog: (284) automatic index on C(manga_id)
01-31 22:45:37.955  6537  6606 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.0 (standard, a6ac2fb, 73, 2022-01-31T20:51Z)
Android version: 8.0.0 (SDK 26)
Android build ID: WAS-LX1A 8.0.0.393(C02)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWWAS-H
Device model: WAS-LX1A
Device product name: WAS-LX1A

### Tachiyomi version

13.0

### Android version

8.0

### Device

Huawei P8 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
same happened to me, huawei p8 lite 2017

**Comment by arkon** [comment]
I can't actually reproduce this since I don't have any means of testing on anything below Android 9.

If anyone else is able to look into this, do go ahead. If any users have more detailed crash logs, do post those as well.

**Comment by sillysack69** [comment]
This is happening on my device too. Must be happening because I have Android 8. Happens to me not when I resume any manga but only if I resume a chapter that has already been downloaded. As long as the chapter is not downloaded, it resumes just fine. Also it only happens when I click the big blue resume button at the lower right hand corner of the screen. As long as I resume using the triangle icon from the history tab, it does not crash either.

I don't know how record this in a log but this is what I came up with:
--------- beginning of main
02-01 14:14:31.805 27037 27037 E ResourceType: Style contains key with bad entry: 0x0101056c
02-01 14:14:31.807 27037 27037 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:14:31.807 27037 27037 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:14:31.807 27037 27037 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:14:31.807 27037 27037 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:14:31.964 27037 27037 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:14:31.964 27037 27037 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:14:31.964 27037 27037 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:14:31.964 27037 27037 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:15:30.572 27037  9690 E SQLiteLog: (284) automatic index on C(manga_id)
02-01 14:15:30.572 27037  9690 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-01 14:15:35.786  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101056c
02-01 14:15:35.789  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:15:35.789  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:15:35.789  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:15:35.789  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:15:35.903  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:15:35.903  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:15:35.903  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:15:35.903  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:15:35.980  9871  9871 E linker  : normalize_path - invalid input: "null", the input path should be absolute
02-01 14:15:36.080  9871  9901 E cr_VariationsSeedLoader: Failed to bind to WebView service
02-01 14:15:36.203  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.218  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.233  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.245  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.266  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.279  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.293  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.309  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.335  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.350  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.370  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.392  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.429  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.441  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.455  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.469  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.518  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.531  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.586  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.605  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.624  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.644  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.657  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.677  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.692  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.705  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.721  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.734  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.753  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.770  9871  9871 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:36.831  9871  9927 E SQLiteLog: (284) automatic index on C(manga_id)
02-01 14:15:36.831  9871  9927 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-01 14:15:44.203  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:15:44.203  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:15:44.203  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:15:44.203  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:15:44.205  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:15:44.205  9871  9871 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:15:44.205  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:15:44.205  9871  9871 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:15:44.315  9871  9871 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
02-01 14:15:44.315  9871  9871 E ACRA    : java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:3)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:789)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.os.Looper.loop(Looper.java:164)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:6944)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
02-01 14:15:44.315  9871  9871 E ACRA    : Caused by: rx.exceptions.OnErrorNotImplementedException: Only fullscreen activities can request orientation
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:4)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:6)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:3)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:17)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:17)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OperatorMaterialize$ParentSubscriber.onNext(OperatorMaterialize.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:6)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:8)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:6)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:4)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.Observable.subscribe(Observable.java:25)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.subscribe(OnSubscribeCombineLatest.java:8)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:15)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:4)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.Observable.subscribe(Observable.java:25)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.Observable.subscribe(Observable.java:7)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.presenter.BasePresenter.subscribeLatestCache(BasePresenter.kt:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.base.presenter.BasePresenter.subscribeLatestCache$default(BasePresenter.kt:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderPresenter$$ExternalSyntheticLambda9.call(R8$$SyntheticClass:13)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.ActionObserver.onNext(ActionObserver.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:8)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	... 7 more
02-01 14:15:44.315  9871  9871 E ACRA    : Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.os.Parcel.readException(Parcel.java:1975)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.os.Parcel.readException(Parcel.java:1913)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:6194)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at android.app.Activity.setRequestedOrientation(Activity.java:5840)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.setOrientation(ReaderActivity.kt:3)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.setManga(ReaderActivity.kt:6)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderPresenter$init$4.invoke(ReaderPresenter.kt:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderPresenter$init$4.invoke(ReaderPresenter.kt:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryCategoryView$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:4)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at nucleus.presenter.RxPresenter$4.call(RxPresenter.java:4)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:1)
02-01 14:15:44.315  9871  9871 E ACRA    : 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
02-01 14:15:44.315  9871  9871 E ACRA    : 	... 39 more
02-01 14:15:44.730 10033 10033 E linker  : normalize_path - invalid input: "null", the input path should be absolute
02-01 14:15:45.016 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.048 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.086 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.119 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.177 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.202 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.235 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.271 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.363 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.409 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.448 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.501 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.588 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.616 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.651 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.685 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.776 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.811 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:45.973 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.018 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.071 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.135 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.171 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.251 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.350 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.424 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.489 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.518 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.549 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.593 10033 10033 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.616 10076 10076 E ResourceType: Style contains key with bad entry: 0x0101056c
02-01 14:15:46.618 10076 10076 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:15:46.618 10076 10076 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:15:46.618 10076 10076 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:15:46.618 10076 10076 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:15:46.730 10076 10076 E ResourceType: Style contains key with bad entry: 0x0101056d
02-01 14:15:46.730 10076 10076 E ResourceType: Style contains key with bad entry: 0x0101058c
02-01 14:15:46.730 10076 10076 E ResourceType: Style contains key with bad entry: 0x01010604
02-01 14:15:46.730 10076 10076 E ResourceType: Style contains key with bad entry: 0x01010605
02-01 14:15:46.771 10076 10076 E linker  : normalize_path - invalid input: "null", the input path should be absolute
02-01 14:15:46.921 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.935 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.948 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.959 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.978 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:46.989 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.001 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.016 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.040 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.052 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.070 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.091 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.117 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.127 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.139 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.151 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.186 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.198 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.246 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.262 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.281 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.300 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.311 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.325 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.339 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.352 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.365 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.378 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.391 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.403 10076 10076 E ApplicationPackageManager: checkSettingsForIconTray value : 0
02-01 14:15:47.457 10076 10144 E SQLiteLog: (284) automatic index on C(manga_id)
02-01 14:15:47.457 10076 10144 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.0 (standard, a6ac2fb, 73, 2022-01-31T20:51Z)
Android version: 8.0.0 (SDK 26)
Android build ID: R16NW.G930LKLU2ESF1
Device brand: samsung
Device manufacturer: samsung
Device name: heroltelgt
Device model: SM-G930L
Device product name: heroltelgt

If anyone has more questions, feel free to ask me.

**Comment by Palloxin** [comment]
with the version 13.1 the bug of the resume button is fixed on my device
