### ISSUE TITLE
Badge when filter is active

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#6754]
### Describe your suggested feature

Please implement this. 
https://media.discordapp.net/attachments/694092459839455243/926581145632649276/Screenshot_20211231-160227_Tachiyomi.png
Its better than tinting the filter icon and will look more close to Material 3. And please lower the dot a little. Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
> Its better than tinting the filter icon

I think we discussed this (which is where you presumably pulled the picture from), there were concerns around which one was more obvious. It's obviously hard to tell since we can't understand how most people think, but one didn't seem any better than the other.

> will look more close to Material 3

Is there an actual guideline around this?

> And please lower the dot a little. 

Why? That image was the default placement done by the standard Material Components library.
