### ISSUE TITLE
Open Manga in Webview enable

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#6975]
### Describe your suggested feature

I noticed that when a source is **not installed** it will prevent opening the manga in webview, same as share button too.

I believe since Tachi is able to access the manga cover and description it should also allow access to the webview button.

(the webview button is not clickable in the image below same as share button too)
![image](https://user-images.githubusercontent.com/39028181/164608648-3a0d61ea-dbc5-40c7-a3e1-64dc1762fb2c.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
This isn't currently feasible without breaking changes in the app as far as I can tell. Could be a thing for 1.x tho

Covers work because the its just a direct link to an image on their website/cdn
Meanwhile, manga links aren't stored in the same way. This is because manga links can be:
 1. complete urls (this is rare)
 2. part of a url that needs to be created into a valid url when trying to open using webview.
 3. actually a link to the API and not the one that is shown on the website. When opening using webview/sharing, they need to be converted (kind of similar to 2.)

These conversions are defined in the source and this is why it is required to install them.
In your particular example (Remanga)
 - a manga url is stored as `"/api/titles/<manga ID>/"`
 - while a cover url is stored as `"https://реманга.орг/<filename of high quality image cover>"`

**Comment by alessandrojean** [comment]
What curche said, it's not possible at the moment. This probably needs to be suggested in 1.x.
