### ISSUE TITLE
App freezes

### ISSUE THREAD

**Issue by Koros1Sama** [tachiyomiorg/tachiyomi#7006]
### Steps to reproduce

Freeze When download chapters

### Expected behavior

The chapters downloading now

### Actual behavior

It doesn't download,It freeze

### Tachiyomi version

0.13.4

### Android version

Android 8.1.0

### Device

Galaxy A6s

### Other details

Maybe i should Clear app data?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I will fill out all of the requested information in this form.

**Comment by persia7emily** [comment]
i freeze with 0.13.4 too.. now back to 0.13.0

**Comment by arkon** [comment]
Does this happen on a fresh install? Does it only start happening after you add things to your library?

**Comment by persia7emily** [comment]
i check update in tachiyomi, then install the apk. after installation, it keep '立', cannot go on.





------------------ Original ------------------
From: arkon ***@***.***&gt;
Date: 周二,4月 26,2022 1:05 上午
To: tachiyomiorg/tachiyomi ***@***.***&gt;
Cc: persia7emily ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [tachiyomiorg/tachiyomi] app freeze (Issue #7006)





 
Does this happen on a fresh install? Does it only start happening after you add things to your library?

**Comment by Patt92** [comment]
just wanted to add. I have an Tolino Vision 6 E-Book Reader with Android 8.1 and the issue started to appear too.
It doesn‘t depend on extensions and is present from 0.13.1+.
All network related operations will let the app freeze completely (search/update/browsing extensions). 

DNS requests show hardly 1 extension getting resolved, mostly none while searching.
The spinning circle won‘t show only a bit and it will never move.

I was confused, because the device was turned off for 1 month and the app doesn‘t work now (was on 0.13.3 and worked start of April).

about the OS: Vanilla Android 8.1 / out of the norm an Allwinner B300 CPU
I don‘t have gapps and installed Webview, because none was present, but this didn‘t change a thing (maybe not necessary).

0.13.0 works razor sharp

**Comment by arkon** [comment]
From #7681: freezes in 0.13.2+ when refreshing the library or searching for new manga

**Comment by arkon** [comment]
Not sure if still happening in 0.14.x.
