### ISSUE TITLE
Tachiyomi Preview freezing when reading a chapter for some time

### ISSUE THREAD

**Issue by raziel100** [tachiyomiorg/tachiyomi#7240]
### Steps to reproduce

1. Start reading any manga in any chapter form any source.
2. After a while the application became frozen and it doesn't work again and need to be forced closed.

### Expected behavior

Read any chapters without freezing the application

### Actual behavior

The application stop working and force me to restart it.

### Tachiyomi version

Tachiyomi Preview r4430

### Android version

Android 11

### Device

Samsung a02

### Other details

I don't know if anyone else is facing the same problem, but with Tachiyomi v0.13.4 (the stable version) it doesn't happen.
I have tried to get a log from "Advanced" menu but it doesn't show anything relevant, only that the application has been started.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
Yeah, I'm use preview too and notice this bug few weeks ago, but the reason me not report it maybe this is an expected issue since dev continue to rewrite parts of the app

But since me saw this issue, I'm will give more information about this bug

When the app freeze , I'm just wait arround 15 or 20s while random touch the screen, and then a popout says close app or wait will spawn, if selected wait, the app will not freeze again and can continue to read manga without force close the app, and if selected close app, it will reopen the app. After that I'm can dump the crash log

![Screenshot_20220615-215253431](https://user-images.githubusercontent.com/101858971/173847963-a63df404-71a9-462b-8d4b-ba079c4a491a.jpg)


Crash log : --------- beginning of main
06-15 21:52:56.571  2662  2662 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
06-15 21:52:59.608  2662  2662 E SQLiteLog: (284) automatic index on C(manga_id)
06-15 21:52:59.608  2662  2662 E SQLiteLog: (284) automatic index on R(manga_id)
06-15 21:52:59.608  2662  2662 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-15 21:53:01.336  2662  2973 E chromium: [ERROR:simple_backend_impl.cc(766)] Simple Cache Backend: cache directory inaccessible right after creation; path: /data/user/0/eu.kanade.tachiyomi.debug/cache/WebView/Default/HTTP Cache/Code Cache/js
06-15 21:53:01.341  2662  2979 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/eu.kanade.tachiyomi.debug/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
06-15 21:53:01.341  2662  2979 E chromium: [ERROR:simple_index_file.cc(582)] Could not reconstruct index from disk
App version: 0.13.4-4466 (standard, 693cc103e, 81, 2022-06-12T15:46Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191008.001.WW_user_100.10.107.123_20210131 release-keys
Device brand: asus
Device manufacturer: asus
Device name: ASUS_Z01R_1
Device model: ASUS_Z01RD
Device product name: WW_Z01RD

**Comment by Architect-Ivy** [comment]
Same problem, never encountered this unresponsive app before updating the app neither on previous versions, frankly it's annoying, it's making me want to install the previous version instead :3

**Comment by THElegend5** [comment]
For me the freeze seems to happen every couple of chapters and in the last 2-3 pages of a chapter only.

**Comment by fatestaynplus** [comment]
This is happening for me as well. While reading for a certain amount of time, the app will freeze while scrolling between pages. If I put my device to sleep while Tachiyomi is running and then wake after an unknown amount of time (Best guess is 30mins to and hour at least), the freeze happens the moment I start to scroll.

The issue does not seem to be specific to any manga / page as I can continue to scroll past normally once the app is restarted.

I'm on the latest app version 0.13.5 (Stable), device is Lenovo P11 Pro tablet (Android 11). This issue is non-existent on the previous app version (0.13.4).

**Comment by DchanN** [comment]
New crashlog ( actually didn't crash) as soon tachiyomi respond again and pop out show close app and wait, selected wait and intermediate go to dump crashlog, this issue when device entering sleep mode while tachiyomi in reading mode, when back to tachiyomi move the page and freeze for a secs until respond again, will update if get freezing by keep reading

--------- beginning of system
--------- beginning of main
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-15 15:12:47.864 13725 19304 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:919)
App version: 0.13.6-4799 (standard, daaa23e8e, 82, 2022-08-14T15:33Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191008.001.WW_user_100.10.107.123_20210131 release-keys
Device brand: asus
Device manufacturer: asus
Device name: ASUS_Z01R_1
Device model: ASUS_Z01RD
Device product name: WW_Z01RD

**Comment by Purkid** [comment]
How were you able to get a crash log for this? When i try to procure a crash log all i see is the device information  and nothing related to the freeze/ crash behaviour.

**Comment by kevin01523** [comment]
Just adding a crashlog for this issue or related issues 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9480805/tachiyomi_crash_logs.txt)

**Comment by DchanN** [comment]
@arkon since using Preview r5085 until last version Preview r5202, in my case freeze never happen again, seems be fixed by #7847 and https://github.com/tachiyomiorg/tachiyomi/commit/7e40680af02505f82fa3655d2d693092c6bd43a1
