### ISSUE TITLE
Quick Save

### ISSUE THREAD

**Issue by Itz1ASh** [tachiyomiorg/tachiyomi#7464]
### Describe your suggested feature

Currently you have to long-tap and then wait a little for the pop-up which is all the way at the bottom of the screen (a pain if you're holding the phone with one hand) then you finally save the image. It might not seem to short now but while you're reading it kinda breaks the immersion. Especially if you are saving a sequence of chapters. So basically instead of a pop-up appearing at the bottom of the page ca n you give us the option to have small pop-up appear near instant where you long tapped. 

### Other details

Also don't darken the rest of the screen when the little pop-up appears it has a similar effect of breaking the immersion.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Itz1ASh** [comment]
*saving a sequence of pages NOT chapters

**Comment by hyoretsu** [comment]
Pop-ups in general are showing up at the bottom of the screen precisely to be comfortable to reach, instead of being all the way at the top of the screen. (since normally you hold your phone from the bottom)
Screen darkening (standard behavior for modals) is precisely to avoid having a weird piece of UI interfering with the manga page. It increases contrast, allows you to focus on it, etc.

That being said, the part about changing the position to your finger's COULD be good.
