### ISSUE TITLE
Tachiyomi crash on library screen.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#7616]
### Steps to reproduce

Open Tachiyomi.
Wait for library screen to load completely.

### Expected behavior

All your manga are shown.

### Actual behavior

Tachiyomi crashes.
https://user-images.githubusercontent.com/63903377/181022730-75e463c9-03d0-42af-8d94-6932a923f71c.mp4

### Crash logs

--------- beginning of system
--------- beginning of main
07-26 19:12:47.917 10376 10463 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
07-26 19:12:47.962 10376 10471 E SQLiteLog: (284) automatic index on C(manga_id)
07-26 19:12:47.962 10376 10471 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.5-4697 (standard, 2b9670979, 81, 2022-07-26T13:07Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: excalibur
Device model: Redmi Note 9 Pro Max
Device product name: excalibur_in

### Tachiyomi version

0.13.5-4697

### Android version

Android 11

### Device

Redmi Note 9 Pro Max

### Other details

The crash probably happens after library loads.
Accessing stuff from history and such works fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment]
I'm facing the same problems and was close to open a issue myself. To help here is my log from the crash

--------- beginning of main
07-26 10:49:34.899 21307 21307 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi.debug
07-26 10:49:34.899 21307 21307 E ACRA    : java.lang.IllegalArgumentException: Index should be non-negative (-1)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListScrollPosition.update-AhXoVpI(LazyListScrollPosition.kt:7)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListScrollPosition.updateScrollPositionIfTheFirstItemWasMoved(LazyListScrollPosition.kt:8)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListState.updateScrollPositionIfTheFirstItemWasMoved$foundation_release(LazyListState.kt:1)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListKt.ScrollPositionUpdater(LazyList.kt:4)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.foundation.lazy.LazyListKt.LazyList(LazyList.kt:41)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.foundation.lazy.LazyDslKt.LazyRow(LazyDsl.kt:12)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at com.google.accompanist.pager.Pager.Pager-upBTbn8(Pager.kt:82)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at com.google.accompanist.pager.Pager.HorizontalPager-7SJ-wSw(Pager.kt:13)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at eu.kanade.presentation.library.components.LibraryPagerKt.LibraryPager(LibraryPager.kt:5)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at eu.kanade.presentation.library.components.LibraryContentKt$LibraryContent$2$2.invoke(LibraryContent.kt:24)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at com.google.accompanist.swiperefresh.SwipeRefreshKt.SwipeRefresh-Fsagccs(SwipeRefresh.kt:59)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at eu.kanade.presentation.library.components.LibraryContentKt.LibraryContent(LibraryContent.kt:57)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at eu.kanade.presentation.library.LibraryScreenKt$LibraryScreen$3.invoke(LibraryScreen.kt:38)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:31)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:3)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:1)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:26)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:9)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:11)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:6)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:21)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:4)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:7)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:9)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:58)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:1)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:10)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:3)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:740)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.os.Looper.loop(Looper.java:246)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8633)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
07-26 10:49:34.899 21307 21307 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
07-26 10:49:34.899 21307 21307 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@a0e7efb, androidx.compose.ui.platform.MotionDurationScaleImpl@3febb18, StandaloneCoroutine{Cancelling}@d072971, AndroidUiDispatcher@9134356]
07-26 10:49:35.458 26584 26584 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
07-26 10:49:38.180 25065 25065 E tachiyomi.debu: Not starting debugger since process cannot load the jdwp agent.
07-26 10:49:38.956 26584 26681 E SQLiteLog: (283) recovered 14 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
07-26 10:49:41.603 25065 26812 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
07-26 10:49:41.830 25065 26828 E SQLiteLog: (284) automatic index on C(manga_id)
07-26 10:49:41.831 25065 26828 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-26 10:49:44.571 25065 26737 E ion     : ioctl c0044901 failed with code -1: Invalid argument
App version: 0.13.5-4697 (standard, 2b9670979, 81, 2022-07-26T13:07Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A022MUBS3BVF1
Device brand: samsung
Device manufacturer: samsung
Device name: a02
Device model: SM-A022M
Device product name: a02ub

**Comment by raziel100** [comment]
@arkon I have tested it in Tachiyomi Preview r4703 and the issue is still happening, I have annexed
[Crash log.txt](https://github.com/tachiyomiorg/tachiyomi/files/9204162/Crash.log.txt)
 the log

**Comment by DchanN** [comment]
I'm use r4703 for a day since yesterday updated, and not encounter any issue crash in Library, maybe because I'm didn't update app to r4697 before when this version has crash issue? (Updating to r4703 from r4687)

**Comment by raziel100** [comment]
> I'm use r4703 for a day since yesterday updated, and not encounter any issue crash in Library, maybe because I'm didn't update app to r4697 before when this version has crash issue? (Updating to r4703 from r4687)

Strange. I'm getting crash every time I try to load library, do you have many Manga in there

**Comment by DchanN** [comment]
> > I'm use r4703 for a day since yesterday updated, and not encounter any issue crash in Library, maybe because I'm didn't update app to r4697 before when this version has crash issue? (Updating to r4703 from r4687)
> 
> Strange. I'm getting crash every time I try to load library, do you have many Manga in there ?

Around 3k

**Comment by raziel100** [comment]
> > > I'm use r4703 for a day since yesterday updated, and not encounter any issue crash in Library, maybe because I'm didn't update app to r4697 before when this version has crash issue? (Updating to r4703 from r4687)
> > 
> > 
> > Strange. I'm getting crash every time I try to load library, do you have many Manga in there ?
> 
> Around 3k

I have around 6k I think? In Tachiyomi Preview r4687 my library works just fine, but until now is broken for me

**Comment by raziel100** [comment]
> I'm use r4703 for a day since yesterday updated, and not encounter any issue crash in Library, maybe because I'm didn't update app to r4697 before when this version has crash issue? (Updating to r4703 from r4687)

I have removed tachiyomi completely and restore the backup and is really working. I believe when I did downgrade something broke? Maybe, I hate importing backup, I don't understand why something that takes less than 3 minutes to create expends more than 6 hours to import

**Comment by DchanN** [comment]
> > I'm use r4703 for a day since yesterday updated, and not encounter any issue crash in Library, maybe because I'm didn't update app to r4697 before when this version has crash issue? (Updating to r4703 from r4687)
> 
> I have removed tachiyomi completely and restore the backup and is really working. I believe when I did downgrade something broke? Maybe, I hate importing backup, I don't understand why something that takes less than 3 minutes to create expends more than 6 hours to import

maybe because you update app to r4697 which have crash issue and either you update or downgrade leftover files from r4697 not fully removed which cause your app still to crash. clean install your make removes all problem files from r4709 and only install fix version from r4703 which make don't have crash issue

**Comment by THElegend5** [comment]
Yeah just reinstalled 4703 and the crash doesn't seem to be happening anymore.

**Comment by raziel100** [comment]
> Yeah just reinstalled 4703 and the crash doesn't seem to be happening anymore.

Yeah, probably something very wrong happened in the old build that broke some information from the database not letting work properly in the new build without cleaning all data and importing backup

**Comment by DchanN** [comment]
@arkon r4703 seems fix library crash, crash only appear when update r4703 from r4697, need clean install r4703 if already updated to r4697 before
