### ISSUE TITLE
 Let the user choose the *entire* backup path 

### ISSUE THREAD

**Issue by JackRoublard** [tachiyomiorg/tachiyomi#7812]
### Describe your suggested feature

When using automatic backups in conjunction with other file synchronization services, Tachiyomi appending the "automatic" folder at the end of the backup path can be really inconvenient.

Not a big deal, but a big QOL improvement for a likely small implementation cost.

Thanks for your time !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
The path is set here https://github.com/tachiyomiorg/tachiyomi/blob/d6f1534ee8c95c7dc450f1cb86d378007e3bf53b/app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt#L145

Related PR #1074

**Comment by arkon** [comment]
I don't think this is going to happen, the app needs to check the files for the max backups functionality and having potential overlap with other random files risks that not working properly.

**Comment by arkon** [comment]
I was thinking overlap between forks, but I guess that'd happen regardless of the subfolder since most forks don't bother changing the format of the file names anyway.

That said, if we ever get to the point that we upgrade our target SDK and need to make users only select a single folder for storage permissions, enforcing a strict folder structure would be the only reasonably safe way for the app to handle backups + downloads + the local source based on a single folder selection.
