### ISSUE TITLE
"Couldn't split downloaded image" Error

### ISSUE THREAD

**Issue by Rockstarmoon** [tachiyomiorg/tachiyomi#7816]
### Steps to reproduce

Tried using the "Auto Split Tall Images" option to download Manhwas. Example: "Close as Neighbors" or Silent War" in Manhwa18.cc Extension. 

### Expected behavior

The downloaded images should split the images into sub numbers like: 01.jpg to 01-01.jpg, 01-02.jpg etc.

### Actual behavior

It gives me a Error "Couldn't split downloaded image" whenever I download a chapter. 

### Tachiyomi version

0.13.6

### Android version

Android 6

### Device

Oppo A57 (2016)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Rockstarmoon** [comment]
I assure you it's not due to a Ram Issue. Because I tried this on J2K since that fork had the feature first. Had the same extension and everything and it woks just fine there.

**Comment by arkon** [comment]
Can you share the crash logs from the advanced settings?

**Comment by Rockstarmoon** [comment]
Tried doing that but whenever I check the crash log.txt file it remains empty. So, it's kind of useless to send an empty text file. But what I've said a while ago is true.

**Comment by DchanN** [comment]
> Can you share the crash logs from the advanced settings?

@arkon  have same issue and get notif like this 
![Screenshot_20220823-015427404 (1)](https://user-images.githubusercontent.com/101858971/185989974-f8e1e6c9-bc4b-441a-b8c3-1bb61dfbe9c4.jpg)
![Screenshot_20220823-015505499](https://user-images.githubusercontent.com/101858971/185990106-2e2fa43a-db58-4de4-91fd-f9e61a04c1bd.jpg)



But I'm try change download location to internal storage and error doesn't happen from the crashlog seems due permission and maybe same with issue #7457 
![Screenshot_20220823-021623395](https://user-images.githubusercontent.com/101858971/185990848-d51a7808-b9cc-47d4-b475-f6374b670a1c.jpg)



And here crashlog 
--------- beginning of system
--------- beginning of main
08-23 02:07:09.208 24216 15545 E ImageUtil: java.io.FileNotFoundException: /storage/F0B8-6CC6/Tachiyomi/Download/ManhuaUS (EN)/Starting From Today I’ll Work As A City Lord/Chapter 440_tmp/001__001.jpg: open failed: EACCES (Permission denied)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at eu.kanade.tachiyomi.util.system.ImageUtil.splitTallImage(ImageUtil.kt:31)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$-7ln7-ORdwCMgD8oWPlcMzNCurA(Downloader.kt:8)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda6.call(Unknown Source:10)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.util.ActionObserver.onNext(ActionObserver.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:3)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:4)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:8)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$2$1.setProducer(OnSubscribeRedo.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Subscriber.setProducer(Subscriber.java:6)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(R8$$SyntheticClass:5)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:4)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:7)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:4)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:8)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Subscriber.setProducer(Subscriber.java:6)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:17)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-23 02:07:09.208 24216 15545 E ImageUtil: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at java.lang.Thread.run(Thread.java:919)
08-23 02:07:09.209 24216 15545 E ImageUtil: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at libcore.io.Linux.open(Native Method)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7340)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-23 02:07:09.209 24216 15545 E ImageUtil: 	... 51 more
08-23 02:07:09.275 24216 15548 E ImageUtil: java.io.FileNotFoundException: /storage/F0B8-6CC6/Tachiyomi/Download/ManhuaUS (EN)/Starting From Today I’ll Work As A City Lord/Chapter 440_tmp/002__001.jpg: open failed: EACCES (Permission denied)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at eu.kanade.tachiyomi.util.system.ImageUtil.splitTallImage(ImageUtil.kt:31)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$-7ln7-ORdwCMgD8oWPlcMzNCurA(Downloader.kt:8)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda6.call(Unknown Source:10)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.util.ActionObserver.onNext(ActionObserver.java:1)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:2)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:2)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:2)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:3)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:4)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:8)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$2$1.setProducer(OnSubscribeRedo.java:1)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.Subscriber.setProducer(Subscriber.java:6)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(R8$$SyntheticClass:5)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:4)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:7)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:1)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:4)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:8)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:1)
08-23 02:07:09.275 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:1)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.Subscriber.setProducer(Subscriber.java:6)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:17)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:1)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.Observable.unsafeSubscribe(Observable.java:2)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:4)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:2)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:2)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at java.lang.Thread.run(Thread.java:919)
08-23 02:07:09.276 24216 15548 E ImageUtil: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at libcore.io.Linux.open(Native Method)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7340)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-23 02:07:09.276 24216 15548 E ImageUtil: 	... 51 more
App version: 0.13.6-4821 (standard, 4b0f54966, 82, 2022-08-20T21:10Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191008.001.WW_user_100.10.107.123_20210131 release-keys
Device brand: asus
Device manufacturer: asus
Device name: ASUS_Z01R_1
Device model: ASUS_Z01RD
Device product name: WW_Z01RD

**Comment by hyoretsu** [comment]
@DchanN's problem is the same as mine, #7457. I was thinking about bumping it when I saw "Long strip split fixes" in latest preview, but since there's already a new issue for it.
