### ISSUE TITLE
Bypassable lock 

### ISSUE THREAD

**Issue by Obii5000** [tachiyomiorg/tachiyomi#7836]
### Steps to reproduce

1.Have "require unlock" on 
2. Close tachiyomi and wait for tachiyomi to lock if you have timer on
3.Open tachiyomi and it should require you to enter your pin but you will leave the app, then come back again and it should be unlocked every time

https://user-images.githubusercontent.com/107339140/185781317-e6314619-0eef-4887-a76b-7c5677ddee1c.mp4

### Expected behavior

Tachiyomi should never unlock until you input the right pin and should only unlock through that method.

### Actual behavior

Tachiyomi unlocks through closing the app and opening it again.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Vivo Y11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DreamyLynn** [comment]
This happens only when a timer is set. The reason is the last_app_closed preference being broken. I have found the following problems with this preference:
* The preference IS updated when closing the app while still in UnlockActivity/after failing authentication
  - There is no check in place to keep the app locked when this happens, resulting in the app unlocking when it shouldn't
* The preference IS NOT updated when terminating the app immediately after closing (the user can do this using the app drawer)
   - This results in the app locking when it shouldn't

**Comment by DreamyLynn** [comment]
A possible fix for the first problem would be setting a preference to `true` whenever `isAppLocked()` (SecureActivityDelegate.kt:68) returns true. A possible fix for the second problem would be setting last_app_closed in the `onTaskRemoved()` function of a service with `android:stopWithTask="false"`. (see https://stackoverflow.com/a/26882533/12979154)
