### ISSUE TITLE
Sorting Order is messed up in the Local Source

### ISSUE THREAD

**Issue by FleetingComet** [tachiyomiorg/tachiyomi#8191]
### Steps to reproduce

Just find a manga/manhwa/manhua with seperated chapter by season and make them to local , for ex:
S1 - Chapter 01
..
S2 - Chapter 01
..
S3 - Chapter 01

### Expected behavior

![Screenshot_20221012_062057_eu kanade tachiyomi](https://user-images.githubusercontent.com/25319699/195210172-e9745bf4-963a-4f35-9645-18cbbf4040ce.jpg)

It should behave like what will appear at the online source

### Actual behavior

![Screenshot_20221012_054123_eu kanade tachiyomi](https://user-images.githubusercontent.com/25319699/195210319-232bf2c1-1ea5-4115-8594-916a9812fb03.jpg)
![Screenshot_20221012_060951_eu kanade tachiyomi](https://user-images.githubusercontent.com/25319699/195210356-e5522775-a3bb-4f49-b505-5a7210d4d6bd.jpg)
![Screenshot_20221012_060859_eu kanade tachiyomi](https://user-images.githubusercontent.com/25319699/195210408-45edbfd4-c945-4b47-a59e-e04697a6f7b4.jpg)

As you can see, the order is messed up even after using all kind of sort

### Tachiyomi version

0.13.6

### Android version

Android 10

### Device

Huawei Y9 Prime 2019 - STK-L22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by abhishekabk5** [comment]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/25201587/195311728-664af7d1-31a0-4c0e-bf02-5e28ac4418b0.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/25201587/195311780-33986210-862d-493d-ae39-198ca7aae057.png">

In eu.kanade.tachiyomi.util.chapter.ChapterRecognition, anything besides chapter+# is removed from the chapter number, including the S# tag, so all the chapters are only sorted per chapter number and the season number is ignored, 

Since I am new to this repo, I would appreciate if someone can tell me what solution is expected here, and I'd be happy to write it up.

**Comment by stevenyomi** [comment]
There's nothing much we can do to the code since it's not feasible to prepend the season number - it will affect other series, and even if you use decimal, 2.11 will be less than 2.2 anyway.

An easy workaround would be for you to batch rename the chapters folders/files and prepend a sort number (like Ch.XXX, with either a sequential index or something like 2002 for S2Ch2) to force the app to recognize the correct order.

**Comment by curche** [comment]
Or, an easier hack which I suggested in #support in Discord where they first reported this:
> Create a separate local manga entry for each Season

[Honestly](https://mangadex.org/title/c1c408f6-3dec-4d62-b6b3-b57e615d933c/wind-breaker), Any title [that](https://www.mangaupdates.com/series.html?id=130325) just resets [Chapter](https://mangadex.org/title/9bcb91e4-df48-4d40-adfd-37d2678ce397/change-h-anthology) Numbers every [Volume](https://mangadex.org/title/f975338c-14d6-4467-9322-678ed0808c6f/josou-shounen-anthology-comic) are just [cursed](https://mangadex.org/title/c02343b3-74e4-4057-b34a-90e08d93f95a/gochuumon-wa-usagi-desu-ka)

**Comment by arkon** [comment]
The app has strong assumptions that chapter numbers don't reset within the same series, so trying to support it would be quite the ordeal.
