### ISSUE TITLE
Drastic performance loss

### ISSUE THREAD

**Issue by frndsvictor** [tachiyomiorg/tachiyomi#8340]
UI for older phones

I have an older phone, the recent updates that altered the app graphically have been extremely damaging to the app's performance on my phone, the input lag was there but not enough to actually bother me, as I do know that my phone is old.

But today, after updating to version 0.14.1, the usage is just unbearable, everything is so slow, the rounded buttons do look nicer, but is that worth the damaging aspect to users with older smartphone models? Is the aim of the developers to make it an app that looks really good but runs badly? one cannot have such an americentric view towards smartphones, the app is used worldwide where there are areas in which you can't just simply buy a better phone for a realistic price.

By making the app so reliant on good specs, you don't only make it bad for people like me, who have and prefer older smartphones, but also make it way less acessible for people living in areas where replacing smartphones with newer models is not the norm.

My suggestion is to make a less resource consuming UI and give the user an option to use that instead of the fancy one that just won't run, if the devs plan on keep updating the app to make it less acessible, at least give us an option to use another UI.

My phone has 1gb of ram, it can run the messaging, banking and essential entertainment apps that I need just fine, the concept that it can't run Tachiyomi which is an app I've been relying on for years, because for some reason the buttons need to be round now, is just absurd to me.

**Comment by specterflare** [comment]
What your talking about has nothing to do with the UI update, it has to do with the ongoing migration to [Compose](https://developer.android.com/jetpack/compose) under the hood. Asking your phone to calculate a few radiuses isn't the issue. As the rewrite is currently a work in progress, performance will be taking a temporary hit. If it really is unusable, downgrade to a version of the app prior to the rewrite. I believe the last non-compose version was 0.13.3.

**Comment by frndsvictor** [comment]
> What you're talking about has nothing to do with the UI update, it has to do with the ongoing migration to [Compose](https://developer.android.com/jetpack/compose) under the hood. Asking your phone to calculate a few radiuses isn't the issue. As the rewrite is currently a work in progress, performance will be taking a temporary hit. If it really is unusable, downgrade to a version of the app prior to the rewrite until it is complete. I believe the last non-compose version was 0.13.3.

Performance has been an issue for me ever since the 0.9.0 update, I don't have enough technical knowledge to point out what caused the performance loss, all I know is that it started when UI changed and it just got worst update after update.

**Comment by arkon** [comment]
> But today, after updating to version 0.14.1, the usage is just unbearable, everything is so slow, the rounded buttons do look nicer, but is that worth the damaging aspect to users with older smartphone models?

Most of the rewrites have the intention of modernizing the codebase so that it's actually easier to make changes to it moving forward.

> one cannot have such an americentric view towards smartphones, the app is used worldwide where there are areas in which you can't just simply buy a better phone for a realistic price.

None of the main app's core maintainers are even American, so that's an oddly prejudiced thing to say. It isn't particularly American to have more advanced technology and requirements today than 15-20 years ago.

> My suggestion is to make a less resource consuming UI

Jetpack Compose is getting performance improvements over time upstream, so you'll reap the benefits as they continue to work on it. We have no intention on deep diving into generic performance issues beyond basic tweaks to ensure it works acceptably on modern mid-range devices.

> at least give us an option to use another UI.

You can use forks that have maintained the older UI at the cost of not supporting newer changes.

> My phone has 1gb of ram

Even [Android Go now requires 2GB of RAM](https://arstechnica.com/gadgets/2022/09/android-13-raises-minimum-system-requirement-to-2gb-of-ram-16gb-of-storage/). 1GB of RAM is not a reasonable amount for any modern technology to work with if you want something user-friendly and safe.
