### ISSUE TITLE
Improve one handed operation in webtoon viewer

### ISSUE THREAD

**Issue by ShakeBake** [tachiyomiorg/tachiyomi#846]
Currently the only way to use the webtoon viewer one-handed in the left hand is to flick/scroll forward with the left thumb. I would suggest configurable areas of the screen where the user can select what action ocurs on a tap. This is well implemented in perfect viewer (picture).
Or for short term allow a left handed operation mode that would switch the scroll forward and the scroll backwards touch areas. Or since 90% of reading is reading forwards, both toch areas could be changed to scroll forward and a scroll backward would have to be done manually (this depends on the user).

Perhaps further on there could even be configurable long touch areas instead of the whole screen. 
![media-20170613](https://user-images.githubusercontent.com/29230146/27096931-8829d1d8-506a-11e7-8959-0df8e291190b.png)

**Comment by Sparh4wk** [comment]
I dont think this is good way to handle it.. Im glad that I can tap "swipe" anywhere to go back and forth..

**Comment by ShakeBake** [comment]
Swiping wouldn't be affected. Just tap zones.

**Comment by Jezza** [comment]
Could just make a left handed mode. 
Pages are laid out right to left.

**Comment by ShaRose** [comment]
Just adding that I'd love this feature too: Personally, the way perfect viewer is the best solely because I can rotate the screen in landscape like in the picture @ShakeBake linked and hold my phone one handed to read without having any issues: right now you would need to scroll with another finger and then tap to go to the next page. I have mine configured so that tapping the far right scrolls forward (or moves to the next page), with tapping the bottom going to the next chapter. Reverse is true for scrolling backward (far left) and previous chapter (top of screen), with the middle working exactly how Tachiyomi works now (showing a progress bar, options, etc). It allows far more customization since you don't have to select an option for each region, or you can make it so you need to long press if you want to.

**Comment by arkon** [comment]
Addressed by more recent changes to viewer navigation and inversion settings.
