### ISSUE TITLE
Manga cover based on chapter read

### ISSUE THREAD

**Issue by sombresu** [tachiyomiorg/tachiyomi#8649]
### Describe your suggested feature

Instead of showing the first or last cover every time no mater what, how about using appropriate cover for the current read progress. Should this feature request be in extension repo?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
This is kinda not possible since 
 1. not all sources have the volume covers
 2. we do not want to rely on anything third-party other than the source itself to get info, when possible

In case you specifically meant MangaDex first and latest cover,
then yes, this should've gone to extension repo
but no, this isn't still possible since there isn't any easy consistent way to grab covers
and the way the app is structured, it might not be able to get current read chapter's volume number and use that to get the cover from the source since those are very different independent things

Sidenote: [Neko](https://github.com/CarlosEsco/Neko/) has something that's pretty similar to what you need (Hint: Open a manga, checkout artworks). This is only for MangaDex tho.
