### ISSUE TITLE
Error in opening zip files in the downloaded chapters 

### ISSUE THREAD

**Issue by 0602RHeze** [tachiyomiorg/tachiyomi#9015]
### Steps to reproduce

1. If set my download path to my SD card. 
2. I've made my download location as tachiyomi recommended tachiyomi folder -> local folder and I also put a ".nomedia".
3. Also save as CBZ archive is on
4. It download as normally as it should be, but when I open the downloaded file it says "error in opening zip files" 
![tachiyomi dl issue](https://user-images.githubusercontent.com/115863223/216441380-dd6bedf9-7ebe-46b2-88fd-de42573844af.jpg)

### Expected behavior

After I download I should work fine like I've download it in my internal storage.

### Actual behavior

I've tried all extension but it always says "error in opening zip files" 

### Tachiyomi version

Tachiyomi Stable 0.14.3

### Android version

Android version 12

### Device

Samsung AO4 4gb ram 

### Other details

![tachiyomi dl location](https://user-images.githubusercontent.com/115863223/216443127-f50d7e1a-512b-4c81-b064-9c3fae3c270f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10780017/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Can you share the crash log too? It may contain a more detailed error even if it didn't crash.

**Comment by 0602RHeze** [comment]
Hi, So here it is. Thanks 
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10779559/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment]
Are those logs taken after reproducing the error message?

**Comment by 0602RHeze** [comment]
- First is not, I'm sorry I didn't know, but now here is it the new one 
[tachiyomi_crash_logs (2).txt](https://github.com/tachiyomiorg/tachiyomi/files/10788553/tachiyomi_crash_logs.2.txt)
- Yes, even the ZIP does not work 
- Yes, it does it works on my internal storage and also sometimes it does work on different folder (sdcard) but only 1-3 chapters are working and sometimes they does open but it has a glitch effects (sorry I don't have a picture of this)

**Comment by LxrdDaryus** [comment]
can confirm this happened to me as well . I'm using a Galxay A01 , I have the downloads pathed to my sdcard . The interesting thing is I changed the file type for a downloaded chapter to .png and it worked but only that one time, it loaded a few pages of the manga and then couldn't load further. 

I also tried to change from downloading .cbz files since that had been the issue but the default opens the manga but it doesn't load the pages and just shows the "Retry" and "Open Webview" buttons which are useless because despite responding to touch effects they don't execute the actual option. 

This is as far as I've got to trying workarounds and what I also encountered that I didn't see mentioned for this issue so far .

hope there's a fix soon , my ride to work has become a pain to endure

**Comment by arkon** [comment]
Merging with #6669
