### ISSUE TITLE
Return the absolute time format back

### ISSUE THREAD

**Issue by Steex** [tachiyomiorg/tachiyomi#9781]
### Describe your suggested feature

My suggestion is about this change (and related): https://github.com/tachiyomiorg/tachiyomi/commit/fe90546821092ce8916445ce515ba51404617d62

Relative timestamps considered by many people as very inconvenient. It's much simpler to me and those people to always see the same format for all dates than to constantly switch mentally between "yesterday" "3 days ago", and "7/25/2023".

Also, absolute dates are much easier to compare in lists of chapter, and they align well in columns.

P.S. If you decide to stick with relative dates could you pls explain why it's ever necessary?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
I assume there is a reason (although usually its visible in the commit message but not in this case)

Maybe its just to avoid needless complexity in the code because currently, there are multiple date format options. Sadly since the app doesn't do analytics (only crashlogs get send and it can be disabled anytime) it is not easy to judge how many users use the setting: the general trend is just to keep the defaults

An alternative I suggest is to remove most of the Date formats in favor of just a toggle between relative and fixed timestamp (eg: ISO 8601) which is what I've seen in most occasions (in websites, its usually a hover action showing you the full timestamp but that's not really practical for tachi I feel)

So.
### _Previously:_
Relative Timestamps: 
  - Off
  - Short
  - Long


Date format: 
  - Default
  - MM/dd/yy 
  - dd/MM/yy 
  - yyyy-MM-dd 
  - dd MMM yyyy 
  - MMM dd, yyyy

### _New Suggestion:_
Toggle Relative dates: 
  - On is relative timestamp (previously, the Long version) 
  - Off is a standard date format (previously, YYYY-MM-DD)

and also alternatively, the date format can just be the Default option and with that, its up to the user to edit their android setting to reflect date formats everywhere (usually means changing their locale completely overkill but its an android limitation)
